### ISSUE TITLE
UserSnippets in *.vue files

### ISSUE THREAD

**Issue by c01nd01r** [octref/vetur#101]
Hello!
UserSnippets don't work inside *.vue.
Look at this screencast: https://youtu.be/6dXVC3oYVsU

vetur 0.5.6.
vscode 1.10.2 (1.10.2)

**Comment by octref** [comment]
Put it as snippet for `vue-html`.

That's the only different part in language naming. You can use css, scss, js snippets for each regions.

**Comment by octref** [comment]
Put an update to the README, thanks!

![image](https://cloud.githubusercontent.com/assets/4033249/24205588/27dba838-0ef2-11e7-8361-fa4d9de366fc.png)

**Comment by c01nd01r** [comment]
Ah, sorry for this... Yep, it is works for me.
Thank you!
