### ISSUE TITLE
[eslint] Missing space before function parentheses.

### ISSUE THREAD

**Issue by sebastianmacias** [octref/vetur#104]
When I format a .vue file the formatter is removing the spaces before the function parentheses and I'm getting warnings like this:

[eslint] Missing space before function parentheses. (space-before-function-paren)

This however doesn't happen with js files (the formatter adds the space when I miss it).

**Comment by octref** [comment]
I'll add an option for it in the next release, since not everyone wants it.

**Comment by caoyi0905** [comment]
@sebastianmacias I think [this](https://stackoverflow.com/a/45855058) will help you solve that problem.

**Comment by yipcma** [comment]
just set this on user settings:

```
  // Add a space before function parenthesis
  "vetur.format.js.InsertSpaceBeforeFunctionParenthesis": true,
```
