### ISSUE TITLE
With 0.5.6 version SCSS with CSS Modules causes syntax  errors

### ISSUE THREAD

**Issue by chanon** [octref/vetur#105]
I am using CSS Modules. In previous version there were no syntax errors, but now there are errors even though it is valid CSS Modules syntax:
![image](https://cloud.githubusercontent.com/assets/357737/24250948/1e52fb3a-100b-11e7-8192-cad16963875b.png)

![image](https://cloud.githubusercontent.com/assets/357737/24250979/35c969e8-100b-11e7-9d50-858a2d9314d0.png)

![image](https://cloud.githubusercontent.com/assets/357737/24250956/239eeb94-100b-11e7-9f9b-de06c24f2302.png)

**Comment by chanon** [comment]
Otherwise if syntax checking can be disabled, that would be fine for me also

**Comment by octref** [comment]
Can you paste the code so I can easily test?

**Comment by chanon** [comment]
```
<style lang="scss" module>
	:global(body.grabbing) {
		.frame {
			cursor: pointer;
		}
	}
</style>
```

**Comment by octref** [comment]
Guess I'll just disable CSS error checking.

**Comment by syonip** [comment]
This is happening to me too.
Did you end up finding a solution/workaround for this?

**Comment by octref** [comment]
`vetur.validation.style: false` is available but I forgot to close this issue.
