### ISSUE TITLE
jsDoc not work

### ISSUE THREAD

**Issue by wanningfe** [octref/vetur#106]
I tried to import a javascript file to a vue component.
but no any comments was imported after that.

**Comment by octref** [comment]
I never use jsdoc so I don't know. Does jsdoc even work in VSCode by default?
You should try to look for TS type definition for the external JS libs you want to use.

**Comment by wanningfe** [comment]
i find it didn't work in VSCode by default.
That has nothing to do with this.

**Comment by octref** [comment]
Thanks. Just saying, with the next release, you should be able to do:

- `npm i -S lodash`
- `npm i -D @types/lodash`
- Type `_.` in JS region and get IntelliSense.
