### ISSUE TITLE
How to turn off `javascript.validate` in vue files when using this plugin?

### ISSUE THREAD

**Issue by githoniel** [octref/vetur#108]
with 
```
"javascript.validate.enable": false,
```

the vscode's javascript.validate still run in *.vue, it does not support some ES7 syntax eg 
```
import('Modules').then((m) => {
     
})
```

**Comment by octref** [comment]
Yeah es7 syntax is not supported. I'll add an option to turn off JS validation.

**Comment by octref** [comment]
Tracked in #179.

**Comment by octref** [comment]
`vetur.validation.script` and `vetur.validation.style` will be available in next release.
