### ISSUE TITLE
Allow zen code\emmet to work in vue templates

### ISSUE THREAD

**Issue by mika76** [octref/vetur#109]
When editing html in vscode usually you can use emmet shortcuts to create html. Please enable this in the vue templates (if possible).

https://code.visualstudio.com/docs/languages/html#_emmet-snippets

**Comment by octref** [comment]
That's the first thing in readme:

![image](https://cloud.githubusercontent.com/assets/4033249/24324455/09b93290-115d-11e7-9f62-d47a6c13ed44.png)

**Comment by mika76** [comment]
Oh brilliant. It never occurred to me that it's working with a config change. A search in issues didn't turn up anything...
