### ISSUE TITLE
ESLint is not working correctly with JSX within .vue files

### ISSUE THREAD

**Issue by Justineo** [octref/vetur#112]
Code to repro:

```vue
<script>
function test () {
  return <span></span>
}
test()
</script>
```

The problem only occurs in `<script>` sections in `.vue` files:

![image](https://cloud.githubusercontent.com/assets/1726061/24536721/e00f19f8-160e-11e7-85b1-c3a975efa4ea.png)

Linting for `.js` files is working as expected:

![image](https://cloud.githubusercontent.com/assets/1726061/24536853/145a602c-1610-11e7-8beb-799d14ae0909.png)

And the file association is correct:

![image](https://cloud.githubusercontent.com/assets/1726061/24536728/e6e1f458-160e-11e7-80db-c66acc805d7b.png)

Following settings is already configured:

```js
{
  "eslint.validate": [
      "javascript",
      "javascriptreact",
      "vue"
  ],
  "eslint.options": {
      "plugins": ["html"] // also tried "vue"
  }
}
```

I'm not sure if it's the right place to ask. Thanks in advance.

**Comment by octref** [comment]
JSX is not yet supported in Vue SFC, I think. If there is an official example, can you send a link to me?

Take a look at (vuepack)[https://github.com/egoist/vuepack] and how it generates a template using JSX. The way seems to be splitting them into js/css files and ESLint works fine.

![image](https://cloud.githubusercontent.com/assets/4033249/24557939/7bc974f4-1607-11e7-8e8e-417f9e08c760.png)

**Comment by yeluoqiuzhi** [comment]
I have an example, can you solve this?
[example](https://github.com/yeluoqiuzhi/vue-jsx-in-vscode)

<img width="782" alt="screen shot 2017-04-06 at 12 00 27 pm" src="https://cloud.githubusercontent.com/assets/9261562/24737397/e070b7ce-1ac0-11e7-9a87-8005106ec5e0.png">

**Comment by rohmanhm** [comment]
Same problem here #115

**Comment by octref** [comment]
Would like to make sure JSX in Vue SFC is actually supported before doing anything.

**Comment by yeluoqiuzhi** [comment]
JSX can compile normally with vue-loader, It's supported in SFC.

Just do this

install dependencies
```shell
npm install\
  babel-plugin-syntax-jsx\
  babel-plugin-transform-vue-jsx\
  babel-helper-vue-jsx-merge-props\
  babel-preset-es2015\
  --save-dev
```

In your .babelrc:

```json
{
  "presets": ["es2015"],
  "plugins": ["transform-vue-jsx"]
}

```

**Comment by octref** [comment]
Just haven't seen any official examples using it this way. I opened issue https://github.com/vuejs/vue-loader/issues/769 for more clarification.

**Comment by yeluoqiuzhi** [comment]
jsx is supported by babel, vue-loader only extract any javascript and compile it with babel

**Comment by rohmanhm** [comment]
Hope this feature available soon https://github.com/Microsoft/vscode/issues/24295

**Comment by octref** [comment]
@rohmanhm Not really. A proper fix would include an updated eslint config for your issue: https://github.com/vuejs/eslint-plugin-vue/issues/9

**Comment by octref** [comment]
This is an ESLint issue to add support for JSX in Vue SFC. Unfortunately there is nothing I can do from my side.

**Comment by octref** [comment]
Just turn off `vetur.validation.script` in the newest version and let ESLint lint your errors.
