### ISSUE TITLE
Error when opening definition of imported function in .vue component

### ISSUE THREAD

**Issue by henri-ihalainen** [octref/vetur#113]
When trying to Go to Definition of foo() function that is imported in the component script tag, an error pops up in VS Code Output

![image](https://cloud.githubusercontent.com/assets/8912981/24549334/7b5e97a0-1621-11e7-9443-c8873e6c5544.png)

![image](https://cloud.githubusercontent.com/assets/8912981/24549401/c9cc6552-1621-11e7-86bd-5b09e5b590eb.png)

**Comment by octref** [comment]
I can repro it. Thanks.

**Comment by octref** [comment]
This doesn't seem to happen with 0.6 for me -- can you try it again?

**Comment by henri-ihalainen** [comment]
It doesn't happen anymore with imported foo() function, but now it happens if you try to go to the definition of bar() method

**Comment by octref** [comment]
Should be fixed with the current master -- will do a release 0.6.5 soon.
