### ISSUE TITLE
insertSpaceBeforeFunctionParenthesis setting not woking in .vue file

### ISSUE THREAD

**Issue by leestar54** [octref/vetur#117]
vscode 1.11+ has been add typescript and javascript format.insertSpaceBeforeFunctionParenthesis settings.
I want to use `fun () {}` to define a function,but when I format document in .vue files script,there is no space before function parenthesis.

insertSpaceBeforeFunctionParenthesis setting works fine in .js files

![2](https://cloud.githubusercontent.com/assets/6147833/24847627/aa52928e-1df4-11e7-9525-83e0648bd90d.gif)

**Comment by octref** [comment]
Thanks. This is already tracked in #107. I'll publish it with updated formatter options from js-beautifier soon.

**Comment by octref** [comment]
https://github.com/octref/vetur/blob/master/docs/formatting.md

**Comment by leestar54** [comment]
Thank you,but after I updated vetur to 6.0,vscode throw an error

> The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

**output**
```
C:\Users\lixin\.vscode\extensions\octref.vetur-0.6.0\client\server\node_modules\vetur-vls\lib\parser\htmlScanner.js:46
            this.len = source.length;
                             ^

TypeError: Cannot read property 'length' of undefined
    at new MultiLineStream (C:\Users\lixin\.vscode\extensions\octref.vetur-0.6.0\client\server\node_modules\vetur-vls\lib\parser\htmlScanner.js:46:30)
    at Object.createScanner (C:\Users\lixin\.vscode\extensions\octref.vetur-0.6.0\client\server\node_modules\vetur-vls\lib\parser\htmlScanner.js:188:22)
    at Object.getDocumentRegions (C:\Users\lixin\.vscode\extensions\octref.vetur-0.6.0\client\server\modes\embeddedSupport.js:9:35)
    at C:\Users\lixin\.vscode\extensions\octref.vetur-0.6.0\client\server\modes\languageModes.js:11:125
    at Object.get (C:\Users\lixin\.vscode\extensions\octref.vetur-0.6.0\client\server\languageModelCache.js:30:33)
    at C:\Users\lixin\.vscode\extensions\octref.vetur-0.6.0\client\server\modes\javascriptMode.js:14:43
    at Object.get (C:\Users\lixin\.vscode\extensions\octref.vetur-0.6.0\client\server\languageModelCache.js:30:33)
    at C:\Users\lixin\.vscode\extensions\octref.vetur-0.6.0\client\server\modes\javascriptMode.js:88:37
    at Array.map (native)
    at Object.resolveModuleNames (C:\Users\lixin\.vscode\extensions\octref.vetur-0.6.0\client\server\modes\javascriptMode.js:80:32)
[Info  - 上午9:43:49] Connection to server got closed. Server will restart.
```
 My project is create by vuejs-templates/webpack from vue-cli and I didn't chang any default things.

it's same as #122

**Comment by octref** [comment]
> My project is create by vuejs-templates/webpack from vue-cli and I didn't chang any default things.

Do you mean if you create a new project with `vuejs-templates/webpack` right now and open it with VSCode and vetur, it still crashes?

**Comment by leestar54** [comment]
No,I mean I didn't change default config things.
I create a new project with vuejs-templates/webpack,vetur works well,it's so strange!
Then I add different files from error project to new project,it's throw error again.
Finally, I found out why this error happened,**because of the .vue extension name**

just in router.js
**throw error**
``import NotFound from '@/views/404.vue'

change to
**no error**
``import NotFound from '@/views/404'

now,it's works well
I hope this will help you to fix this bug
