### ISSUE TITLE
Adding colon in attributes breaks syntax highlighting

### ISSUE THREAD

**Issue by kirtangajjar** [octref/vetur#118]
Here is a test case

```
<template>
  <v-layout>
    <v-sider style="overflow-y: scroll">
      <AddNewDataSource />
      <TreeView :sourceData=this.globalData />
    </v-sider>
    <v-content>
      <GraphView :sourceData=this.graphData />
    </v-content>
    <v-sider>
      abc
    </v-sider>
  </v-layout>
</template>
```
...and here is what happens
![screen shot 2017-04-14 at 10 36 16 pm](https://cloud.githubusercontent.com/assets/8456197/25050194/a64d7f74-2163-11e7-9a5e-929d23551cbc.png)

**Comment by octref** [comment]
I think your syntax is wrong. You need double/single quotes around the value like so:

`<TreeView :sourceData="this.globalData" />`

Also see #58.

**Comment by kirtangajjar** [comment]
Oh! Never noticed that. Thanks 👍 

Well there's a question -  If it works works without quotes, don't you think it is a valid vue syntax? The docs may not use it, but it still could be valid. And if that's the case, don't you think that syntax highlighting should not break like that?

**Comment by octref** [comment]
I've never used it that way -- can you find a doc or official example that include such usage? If so I'll add support.
