### ISSUE TITLE
[js-intellisense] imports aren't working

### ISSUE THREAD

**Issue by cynecx** [octref/vetur#119]
Hey,

I would like to report a bug or more like a feature request in case this isn't a bug.

The bug is really easy to reproduce: Create a vue file with javascript inside, then try to import anything and it's not resolving the imports. However, it works (imports and whole modules resolution) when I separate the vue file into a vue and javascript file by referencing the javascript through the src tag.

**Comment by cynecx** [comment]
I've just realized that this issue is a duplicate. See #26 .

**Comment by octref** [comment]
Yea it's already in master. Will be available in 0.6. Need a bit more time to work on it.

**Comment by cynecx** [comment]
@octref Is it possible to somehow build this extension from master. Do you have any instructions?

I've tried following: cloned the repo -> `npm install` for client and server -> `npm run compile` for client and server. Then I've packaged the extension with `vsce package` and installed directly in vscode.

This isn't working though. I am getting an error:

```
client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46
            this.len = source.length;
                             ^

TypeError: Cannot read property 'length' of undefined
```

**Comment by octref** [comment]
@cynecx I haven't seen that before. Let's track it in #122.
