### ISSUE TITLE
vscode 1.8 may help this project.

### ISSUE THREAD

**Issue by hujianxin** [octref/vetur#12]
https://code.visualstudio.com/updates#_javascript-language-support-in-html

Vscode gets full JavaScript language support in HTML files. So this feature may help

**Comment by octref** [comment]
Thanks, I'm aware of it and already made a prototype with its code.
Now I have a local implementation with a few bugs. I'll push once I consider it done. (Probably next 1-2 weeks). Stay tuned :-)

**Comment by hujianxin** [comment]
@octref Thanks!
