### ISSUE TITLE
no IntelliSense for js

### ISSUE THREAD

**Issue by muermaru** [octref/vetur#120]
![image](https://cloud.githubusercontent.com/assets/12495960/25111112/9ec1848e-241b-11e7-80ad-0c31229ef174.png)
my vscode's version is 1.10.2, it is no intelliSense for js codes(like 'for' or 'if' and so on),but for html it works well

![image](https://cloud.githubusercontent.com/assets/12495960/25111704/244ad8e6-241f-11e7-8958-370d10ac3858.png)
there are my extensions

![image](https://cloud.githubusercontent.com/assets/12495960/25111719/33be411e-241f-11e7-95a9-003e988b81bc.png)
and my settings

**Comment by muermaru** [comment]
I just update my vsc to 1.11.2, now the intelliSense for js is works well...

**Comment by octref** [comment]
Also see #26 and #119. Wait for the upcoming 0.6 release...
