### ISSUE TITLE
Add option to configure initial indent for <style> and <script>

### ISSUE THREAD

**Issue by octref** [octref/vetur#121]

**Comment by mubaidr** [comment]
Does this issue or improvement belongs to this:
Vetur on save converts this code;
```
<script>
  import appHeader from './Layout/Header'
  import appFooter from './Layout/Footer'
</script>
```
To this
```
<script>
import appHeader from './Layout/Header'
import appFooter from './Layout/Footer'
</script>
```

**Comment by octref** [comment]
@mubaidr Yes I'm planning to have it before 0.7.

**Comment by mubaidr** [comment]
@octref Awesome, i was about to create a new issue for the same! Thanks. Waiting for the update.

**Comment by octref** [comment]
`vetur.format.styleInitialIndent` and `vetur.format.scriptInitialIndent` are added.

**Comment by octref** [comment]
Published as 0.6.9.

**Comment by mubaidr** [comment]
Awesome!

**Comment by heeboA** [comment]
Could we have this option for the template-tag aswell?

**Comment by octref** [comment]
@heeboA No.
