### ISSUE TITLE
Vetur 0.6.0 The Vue Language Server server crashed 

### ISSUE THREAD

**Issue by jingzheshan** [octref/vetur#122]
Hi,

After I installed 0.6.0 it throws following error. Here is the error log screenshot

![2222](https://cloud.githubusercontent.com/assets/2770401/25207349/03d5513c-25c2-11e7-9492-63e4b1b534d9.PNG)

Thanks for your help,
Jing

**Comment by octref** [comment]
Can you try projects like https://github.com/vuejs/vue-hackernews-2.0 and https://github.com/vuejs-templates/webpack and see if this happens to them as well?

Also, are you working on a project that you've been using vetur with? Seems past language cache is messing up with the new module resolution.

**Comment by jingzheshan** [comment]
Vetur is a great tool, I used this plugin since current project started. 
I tried on  https://github.com/vuejs/vue-hackernews-2.0 and seems all normal, however I did find one minor issue. If I keep formatting document (shift + alt + f), indenting keeps happening.

![animated](https://cloud.githubusercontent.com/assets/2770401/25209384/ec1b0e9e-25ce-11e7-9bd9-d41e570b1792.gif)

Cheers,
Jing

**Comment by octref** [comment]
Don't close it yet -- let me figure it out as it might be happening to other people too.

For the project that's crashing, do you have a jsconfig or tsconfig inside it?

**Comment by ninja-1** [comment]
Also having this problem on a project that I've been using vetur with before the update. I don't have a jsconfig or tsconfig in the project.

> Seems past language cache is messing up with the new module resolution.

Is there a way to clear the cache? I've tried reinstalling vetur with no success.

**Comment by jingzheshan** [comment]
Here is my tsconfig.json (no jsconfig)
{
  "compilerOptions": {
    "allowJs": true,
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "lib": [
      "dom",
      "es2015",
      "es2015.promise"
    ],
    "types": [
      "vue-typescript-import-dts",
      "jquery",
      "semantic-ui",
      "lodash"
    ],
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true
  },
  "include": [
    "client/**/*.ts"
  ],
  "compileOnSave": false
}

**Comment by wodeguaiguai** [comment]
Also having this problem on my project After the update!

**Comment by octref** [comment]
@jingzheshan Can you try backup that `tsconfig`, remove it from your project, and see if vetur still crashes?
Seems you are using `tsconfig` to compile some ts code, but `vetur` thought that was meant for vue code too, so vetur ends up trying to resolve a `.vue` file that's outside `"client/**/*.ts"`.

**Comment by octref** [comment]
For people having problems -- it would be great if you can find a sample project like `vue-hackernews-2`, or some `vue-templates` and still make vetur crash.

Basically I need a project where I could repro the problem and the bug can be easily resolved.

**Comment by octref** [comment]
I got the repro -- give me some time to look into it.

**Comment by cynecx** [comment]
Unfortunately, it's still not fixed for me.

```
/home/cynecx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566
            throw new Error("start < 0");
            ^

Error: start < 0
    at createTextSpan (/home/cynecx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566:19)
    at Object.createTextSpanFromBounds (/home/cynecx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10575:16)
    at getErrorSpanForNode (/home/cynecx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:7075:19)
    at createDiagnosticForNodeInSourceFile (/home/cynecx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6999:20)
    at Object.createDiagnosticForNode (/home/cynecx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6995:16)
    at /home/cynecx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21582:58
    at Object.forEach (/home/cynecx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:1423:30)
    at declareSymbol (/home/cynecx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21581:28)
    at declareModuleMember (/home/cynecx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21600:28)
    at declareSourceFileMember (/home/cynecx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:22646:19)
[Info  - 8:52:19 PM] Connection to server got closed. Server will restart.
```

My code base is quite big, so I am not sure what is causing this.

**Comment by guzz** [comment]
I´m also having this problem in a project created from vue-browserify template...

**Comment by vicvinc** [comment]
am I loosing the right config file for this question? my editor didn't crash on Vue-hacker-news and Vue-template.. but my app goes on crash... :(

**Comment by octref** [comment]
@vicvinc Try this: https://octref.github.io/vetur/setup.html#overall
Only include your frontend code.

**Comment by vicvinc** [comment]
@octref  thx vry mch!
