### ISSUE TITLE
Error with vue language server

### ISSUE THREAD

**Issue by coderdiaz** [octref/vetur#126]
Hi guys,
I have this issue with vue components every time I save a .vue file throws that exception

![image](https://cloud.githubusercontent.com/assets/26385863/25242852/b2f219f4-25c0-11e7-92f8-26643f49c2aa.png)

**Comment by octref** [comment]
Dup of #122 and #123. Upgrade to 0.6.1.

**Comment by coderdiaz** [comment]
@octref Thanks
