### ISSUE TITLE
Look into adopting latest TS/JS grammar

### ISSUE THREAD

**Issue by octref** [octref/vetur#13]
Seems ternary operator in vue-directive works with latest insider.

**Comment by IAMJ** [comment]
这插件是针对 Vue 2 的？什么时候可以支持代码提示，现在 vue 文件里的 scss / js 等虽然有高亮但还是没有代码提示

**Comment by octref** [comment]
@IAMJ It's for Vue 2. You can track progress in #2.

**Comment by octref** [comment]
Current grammar works fine.
