### ISSUE TITLE
0.6.1 when use copy hot key. Automatically pops up the error log 

### ISSUE THREAD

**Issue by Moerj** [octref/vetur#134]
![qq20170421-174513](https://cloud.githubusercontent.com/assets/13795438/25272748/a70f358a-26bb-11e7-9bd6-895495d7c29f.jpg)

when i copy a object name in vue data. the error log will pops up
the vetur version 0.6.1

the previous version 0.6.0 is ok

**Comment by c01nd01r** [comment]
+1
<details>
 <summary>My log</summary>
<pre>
[0421/150539:ERROR:tcp_listen_socket.cc(76)] Could not bind socket to 127.0.0.1:6005
[0421/150539:ERROR:node_debugger.cc(86)] Cannot start debugger server
/Users/c01nd01r/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46
            this.len = source.length;
                             ^

TypeError: Cannot read property 'length' of undefined
    at new MultiLineStream (/Users/c01nd01r/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46:30)
    at Object.createScanner (/Users/c01nd01r/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:188:22)
    at Object.getDocumentRegions (/Users/c01nd01r/.vscode/extensions/octref.vetur-0.6.1/client/server/modes/embeddedSupport.js:9:35)
    at /Users/c01nd01r/.vscode/extensions/octref.vetur-0.6.1/client/server/modes/languageModes.js:11:125
    at Object.get (/Users/c01nd01r/.vscode/extensions/octref.vetur-0.6.1/client/server/languageModelCache.js:30:33)
    at /Users/c01nd01r/.vscode/extensions/octref.vetur-0.6.1/client/server/modes/javascriptMode.js:14:43
    at Object.get (/Users/c01nd01r/.vscode/extensions/octref.vetur-0.6.1/client/server/languageModelCache.js:30:33)
    at Object.getScriptKind (/Users/c01nd01r/.vscode/extensions/octref.vetur-0.6.1/client/server/modes/javascriptMode.js:69:33)
    at Object.getScriptKind (/Users/c01nd01r/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:70920:31)
    at HostCache.createEntry (/Users/c01nd01r/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:84794:36)
[Info  - 3:05:56 PM] Connection to server got closed. Server will restart.
[0421/150556:ERROR:tcp_listen_socket.cc(76)] Could not bind socket to 127.0.0.1:6005
[0421/150556:ERROR:node_debugger.cc(86)] Cannot start debugger server
[Error - 3:18:32 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 3:18:32 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
</pre>
</details>

**Comment by octref** [comment]
Can't repro it. Can you two try to find a minimal repro case and paste the code here?

**Comment by Moerj** [comment]
![qq20170421-231731 2x](https://cloud.githubusercontent.com/assets/13795438/25284171/cd757dd8-26e8-11e7-9e00-ef354ed69ec6.jpg)

`<style lang="scss">
    .msgContent{
        border: 1px solid #eee;
        margin-top: 15px;
        color: rgba( black, .5);
        >.empty{
            text-align: center;
            padding: 15px;
        }
    }
</style>

<template>
    <div>
        <el-tabs v-model="activeMailTabs" type="card" @tab-click="mailTabsClick">
            <el-tab-pane label="收件箱" name="getMail">
                <el-tabs v-model="activeMsgType" @tab-click="msgTypeClick">

                    <el-tab-pane label="全部信息" name="all">

                        <ui-dropsearch> 
                            <el-select v-model="msgSelected" placeholder="请选择">
                                <el-option v-for="item in msgType" :value="item.value">
                                </el-option>
                            </el-select>
                            <el-select v-model="msgSelected" placeholder="请选择">
                                <el-option v-for="item in msgType" :value="item.value">
                                </el-option>
                            </el-select>
                            <el-input class="ui-input-w" v-model="msgSearch" placeholder="请输入内容"></el-input>
                        </ui-dropsearch>

                        <el-button type="">发送站内信</el-button>
                        <el-button type="">标记本页已读</el-button>
                        <el-button type="danger">删除</el-button>

                        <div class="msgContent">
                            <p v-if="!msgData" class="empty">暂无记录</p>
                            <div v-else>

                            </div>
                        </div>

                    </el-tab-pane>

                    <el-tab-pane label="未读信息( 0 )" name="unread">未读信息</el-tab-pane>

                    <el-tab-pane label="已读信息" name="read">已读信息</el-tab-pane>

                </el-tabs>
            </el-tab-pane>
            <el-tab-pane label="发件箱" name="setMail">发件箱</el-tab-pane>
        </el-tabs>
    </div>
</template>

<script>
    export default {
        data() {
            return {
                activeMailTabs: 'getMail',
                activeMsgType: 'all',
                msgType: [{
                    value: '全部'
                }, {
                    value: '标题'
                }, {
                    value: '内容'
                }, {
                    value: '收件人'
                }, {
                    value: '接受时间'
                }, {
                    value: '状态'
                }],
                msgSelected: '全部',
                msgSearch: '',
                msgData: null,
            };
        },
        methods: {
            mailTabsClick(tab, event) {
                // console.log(tab, event);
            },
            msgTypeClick() {

            }
        },

    };

</script>
`

**Comment by Moerj** [comment]
[mail.vue.zip](https://github.com/octref/vetur/files/947502/mail.vue.zip)

**Comment by Moerj** [comment]
Moerj/GOPIGGY
this is my project. Hope it can help you.

**Comment by octref** [comment]
I tried vetur with your project, still can't repro...
Does 0.6.2 have any effect with this bug?

**Comment by Moerj** [comment]
And did not solve the problem😔

![qq20170425-223347 2x](https://cloud.githubusercontent.com/assets/13795438/25390978/a640a64e-2a07-11e7-9cf9-a926993300c4.jpg)

**Comment by Moerj** [comment]
By the way. I use macOS and Chinese system language. Is it a system problem?

**Comment by Moerj** [comment]
where can I download the 0.5.6 version? I can not work for the current version.

**Comment by octref** [comment]
https://github.com/octref/vetur/files/947389/vetur-0.5.6.vsix.zip

**Comment by Moerj** [comment]
ok i got it. thanks

**Comment by Moerj** [comment]
You need to be replicated many times to reproduce the problem

**Comment by bannermiao** [comment]
I have the same problem
GIF: http://www.ms580.cn/1.gif

**Comment by Moerj** [comment]
0.6.3 also have this problem

**Comment by octref** [comment]
Fix wil be in 0.6.5.

**Comment by cubodehelio** [comment]
I'm experiencing the same issue when copy in `0.6.4`

**Comment by Moerj** [comment]
@ @octref 你的0.6.5版本多久来啊

**Comment by octref** [comment]
Published a few minutes ago.

**Comment by asphub** [comment]
**Getting error on output window**

```
[Error - 12:07:41 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
```

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 15.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|minify|HookyQR|0.3.0|
|html-css-class-completion|Zignd|1.2.1|
|vscode-svgviewer|cssho|1.4.1|
|githistory|donjayamanne|0.2.0|
|Angular2|johnpapa|2.3.2|
|csharp|ms-vscode|1.10.0|
|debugger-for-chrome|msjsdiag|3.1.2|;


---
