### ISSUE TITLE
Small issue with commented out <script> tags

### ISSUE THREAD

**Issue by brianjorden** [octref/vetur#139]
First off, this is something silly I was struggling with and really shouldn't be a common or typical issue that people run into, but I'd rather save others the time/effort/frustration by mentioning it.

There seems to be an "issue" where a `<script>` or `</script>` tag appears in a commented out section within the regular script block. I haven't completely tested the different scenarios, but when glancing through the code it seems the parser is just trying to match opening and closing instances and ignorant of if they are currently commented out.

I completely understand that this may be a challenge in how things just have to be done with parsing of a single file component. If that is the case, it may just be worth a line item mention in the documentation somewhere.

I managed to land on this issue because I had been writing my components with this in the *.vue files: `<script lang="ts" src="whatever.vue.ts"></script>` in order to get TypeScript intellisense. When testing vetur I had the not so great idea of just commenting that line out with `//` inside a regular `<script lang="ts">` block. I then had different results depending on if that commented out line was at the start or end of the block in different files.

The simplest way to reproduce this in a live environment is to just add a line somewhere in a .vue file of `// </script>` and you'll either see vetur fail completely (actually maybe it is eslint failing?) or you'll see stuff work above that line and not below it. Following screenshots give a little bit of an example:

![image](https://cloud.githubusercontent.com/assets/12365487/25292611/eda11570-26a4-11e7-8b27-e15dcc77ae0f.png)

![image](https://cloud.githubusercontent.com/assets/12365487/25292632/0245dc0e-26a5-11e7-9e96-0c0b651a64ae.png)

**Comment by octref** [comment]
`vue-template-compiler` doesn't support such use cases (embedded `<script>`, even in comments). So vue itself wouldn't support such a feature either.

**Comment by octref** [comment]
The correct way to use `<script>` for loading other files is either to
- Specify it in the outer region, not inside another `<script>`
- Require / import it in the `<script>` region

**Comment by brianjorden** [comment]
Really not a big deal or issue to me, but just for clarity, the code compiles and works without issue if a <script> tag is commented out, but it is just knocking down the language server stuff it seems. Part of the reason for opening an issue was to mention it as something to be aware of in case there were any other related issues.
