### ISSUE TITLE
emmet for css/sass/scss/less/stylus

### ISSUE THREAD

**Issue by jing2si** [octref/vetur#14]
This plugin is the best in the vue plugin.
Whether emmet can support css/sass/scss/less/stylus.

**Comment by octref** [comment]
Thanks, I'll take a look once I'm done with the language server.

**Comment by octref** [comment]
I added instruction in readme for setting up emmet in css/scss/less:

> Add the following to your settings:

    "emmet.syntaxProfiles": {
      "vue": "css"
    }

Now you can use css expansions anywhere in your vue file. However, this isn't ideal. It doesn't limit css expansions to `<style>` tags. If you have `bg` in `<script>` section and pressed expand, it'll expand to `background` too.

I'll work on improving the language server to provide emmet expansion as CompletionItems. Anyway later I'll do the same for Vue API completion.
