### ISSUE TITLE
0.6.1 code helper cpu occupied 100% on mac. My English is not very good ,sorry

### ISSUE THREAD

**Issue by hj2060** [octref/vetur#141]

**Comment by octref** [comment]
Open general issue at https://github.com/Microsoft/vscode

WIthout any info I can't help you further.

**Comment by gonzaloserrano** [comment]
I upgraded to latest (`1.23.1`) VSCode and got this issue. After enablind and disabling all plugins I found that `Vetur` causes it somehow. How could I help you debugging this? I can reproduce it.

**Comment by gonzaloserrano** [comment]
Sorry, dupe of https://github.com/vuejs/vetur/issues/789
