### ISSUE TITLE
Extension host terminated unexpectedly [0.6.2]

### ISSUE THREAD

**Issue by ppasieka** [octref/vetur#147]
It happed in version 0.6.2

I'm assuming that problem has it roots in my workspace setup which is very big [old] hybrid 
- use babel in connection with vue
- I also use Typescript in part of the solution 

So in my packages.json you will find babel and typescript packages. I also have .babelrc and tsconfig.json next to each other.

1. When I open vue file and try to trigger intellisense (Ctrl + Space) 
2. Loading... shows
3. After some time editor area does not react on any key-presses. I can tape anything but nothing will show up on screen. Cursor is blinking - windows is not frozen
4. Alert with message is showing up "Extension host terminated unexpectedly"

This is what I found in Vue language server:
```
Error: Could not find file: 'c:\Users\Piotr\...{project_path}.........\TaskDialog.vue'.
    at getValidSourceFile (C:\Users\Piotr\.vscode\extensions\octref.vetur-0.6.2\client\server\node_modules\typescript\lib\typescript.js:84996:23)
    at Object.getSyntacticDiagnostics (C:\Users\Piotr\.vscode\extensions\octref.vetur-0.6.2\client\server\node_modules\typescript\lib\typescript.js:85204:52)
    at Object.doValidation (C:\Users\Piotr\.vscode\extensions\octref.vetur-0.6.2\client\server\modes\javascriptMode.js:129:49)
    at C:\Users\Piotr\.vscode\extensions\octref.vetur-0.6.2\client\server\htmlServerMain.js:142:43
    at Array.forEach (native)
    at validateTextDocument (C:\Users\Piotr\.vscode\extensions\octref.vetur-0.6.2\client\server\htmlServerMain.js:140:59)
    at Timeout._onTimeout (C:\Users\Piotr\.vscode\extensions\octref.vetur-0.6.2\client\server\htmlServerMain.js:134:9)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[Info  - 07.17.31] Connection to server got closed. Server will restart.
C:\Users\Piotr\.vscode\extensions\octref.vetur-0.6.2\client\server\node_modules\typescript\lib\typescript.js:84996
                throw new Error("Could not find file: '" + fileName + "'.");
```

and here is screenshot from Dev Tools console

![image](https://cloud.githubusercontent.com/assets/2170707/25370105/c3437958-2988-11e7-920e-921d322ad8b6.png)

After work (or during next weekend) I'll try to prepare minimal solution to demonstrate case. Either way I create this issue hoping that maybe it will be helpful

PS> In my second project which is based on Typescript+vue ( i use lang="ts" in script tag) extension seems to work

**Comment by BelinChung** [comment]
VLS error log (vetur v0.6.2)
```
[Error - 2:32:17 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 2:32:17 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'parameters' of undefined
  Code: -32603 
[Error - 2:40:29 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'parameters' of undefined
  Code: -32603 
```

**Comment by Moerj** [comment]
me too

**Comment by ppasieka** [comment]
I followed steps presented by @chanon in #155 issue and setting proper include array in tsconfig.json solve crashing server problem

Now question is if it is possible to set custom tsconfig.json file in workspace.

**Comment by SirM2z** [comment]
I am also experiencing this issue.

**Comment by octref** [comment]
@ppasieka Glad you figured it out. Yes if you are using `tsconfig.json`, you should either 

- Have no `include`. This includes every source file in your folder except those in `exclude`
- Make sure all vue files will be inside `include`

**Comment by octref** [comment]
Let me add a detection and information dialog instead of crashing.
