### ISSUE TITLE
Support for word based suggestion

### ISSUE THREAD

**Issue by nizulzaim** [octref/vetur#15]
Hi,

I notice that word based suggestion not enable in .vue file. Really hope it can be done by you as your work is really awesome!

**Comment by octref** [comment]
I just released 0.2 which includes intelliSense (code completion) for html/css/scss/less/js. Have you upgraded yet?

Can you also clarify `word based suggestion`? Do you mean intelliSense (code completion), code action (red squiggles under words), or something else?

**Comment by nizulzaim** [comment]
Hi, I already update but actually not all of code will include in intellisense. The alternative way is make it work after follow like this page settings tutorial so that every single word in page will display: 

[https://code.visualstudio.com/docs/editor/intellisense](https://code.visualstudio.com/docs/editor/intellisense)

**Comment by nizulzaim** [comment]
![screenshot from 2017-01-03 21-17-13](https://cloud.githubusercontent.com/assets/9782607/21608862/0d6b8b4c-d1fa-11e6-875e-896d1e31b5f7.png)


See here, when i try to type `this.activeId`, the suggestion will not show up.

**Comment by nizulzaim** [comment]
ok actually i test more. and then found that only variable in scope can have suggestion. but not whole page. like in declare in data.

**Comment by octref** [comment]
This extension was meant to provide semantically correct intelliSense -- same as VSCode's JS language service. Adding word-based intelliSense might help your case, but it reduces reliability of the intelliSense, as suggestions could be wrong. So I'm not sure that's the way to go.

With that said, I do have plan to eval the component (or analyze its AST) to find props/computed for enhanced intelliSense (both for values in v-if, v-show, etc and js in `<script>`). It'll take some time though.

They are the last two items in the [roadmap](https://github.com/octref/vetur#roadmap).

**Comment by nizulzaim** [comment]
nice to hear that! Thanks. For now, i will just wait for it.
