### ISSUE TITLE
An option to use "js-beautify" for js files

### ISSUE THREAD

**Issue by mehyaa** [octref/vetur#150]
Hi,

Can you add an option to set js formatter to "js-beautify"?

**Comment by octref** [comment]
This extension doesn't deal with js files.

**Comment by mehyaa** [comment]
I'm talking about formatting of **embedded js** under **script** part of *.vue files which are formatted by "TypeScript's language service" as of now. Not plain js files.

**Comment by octref** [comment]
I can possibly add it in the future but it's of pretty low priorities now compared to other issues.
