### ISSUE TITLE
Use .jsbeautifyrc for "js-beautify" settings if exists

### ISSUE THREAD

**Issue by mehyaa** [octref/vetur#151]
Hi,

Can you use .jsbeautifyrc file in project to format code when formatting with "js-beautify" instead of using extension settings?

**Comment by octref** [comment]
No. A lot of the settings doesn't make sense in the context for vue files so I only expose a part of them.

**Comment by mehyaa** [comment]
Isn't it easier using a seperate file which "js-beautify" can use directly, instead of wrapping and exposing your own settings?

**Comment by octref** [comment]
Only a subset of these settings make sense for vue.
People will open issues like "why this setting has no effect".
And the js setting is based on TypeScript's formatter, not `js-beautify`.
