### ISSUE TITLE
Request textDocument/hover failed

### ISSUE THREAD

**Issue by rafaelpimpa** [octref/vetur#152]
The only vue extension I have is vetur.

I'm constant getting this error when hovering props/methods/etc:

```
[Error - 14:01:35] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'parameters' of undefined
  Code: -32603 
```

Anything I'm missing?

**Comment by octref** [comment]
Please provide:

- vetur/vscode version
- a screenshot or gif showing the error

**Comment by SzHeJason** [comment]
+1
vsCode/Vetur version is latest
output error : 
![image](https://cloud.githubusercontent.com/assets/20609396/25575663/eb229ee2-2e8b-11e7-915b-715bdd5fee1a.png)

**Comment by octref** [comment]
Fix will be available in 0.6.5.

**Comment by yinheli** [comment]
version: 0.6.11

```
[Error - 9:04:33 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'parameters' of undefined
  Code: -32603 
```

**Comment by octref** [comment]
Keep tracking it in #191.
