### ISSUE TITLE
postcss checking in v0.6.2 is wrong !  

### ISSUE THREAD

**Issue by yeluoqiuzhi** [octref/vetur#153]
I used [postcss-salad](https://github.com/ElemeFE/postcss-salad), It just a postcss plugin bundle...

It isn't standard css and It needn't to be checked.  I Just want to **disable css checking**, How should I do ?

Error like this (v0.6.2):

![image](https://cloud.githubusercontent.com/assets/9261562/25414176/922c2d94-2a62-11e7-808e-a736587f7201.png)

You can look at [postcss-bem](https://github.com/kezzbracey/postcss-bem) directly.

**Comment by octref** [comment]
Will add option later.

**Comment by yeluoqiuzhi** [comment]
Thanks.

**Comment by octref** [comment]
When using postcss, you should use `<style lang="postcss">` otherwise there is no way for me to tell what's inside the style tag.

Disable validation for certain region is tracked in #179.

I should really take time to finish my PR for https://github.com/vuejs/vue-loader/issues/680...

**Comment by octref** [comment]
`vetur.validation.script` and `vetur.validation.style` will be available in next release.
