### ISSUE TITLE
support @types intellisense in the .vue file

### ISSUE THREAD

**Issue by kinanson** [octref/vetur#17]
I hope can get typings like @types/jquery in the vue file.I can get this feature in the js file.but I can't trigger intellisense in the vue file.Will you support this?thank you and best regard

**Comment by octref** [comment]
That's on the plan. Thanks for reporting.

**Comment by kinanson** [comment]
Hello.I find another problem with vue file.I had install javascript snippet so I can get clg snippet or console intellisense.But I can't get this features in the vue associations.If I remove this settings and then console or clg(it's mean console.log())come back.can you fix this?Because I like this tool can help me scss in the vue file.So I hope this plugins can better then now.
thank you a lot.

**Comment by octref** [comment]
@kinanson Do you mean you want to use your JS snippets in `<script>` blocks?

**Comment by kinanson** [comment]
yes.

**Comment by octref** [comment]
I'll track that in #22.

**Comment by octref** [comment]
Original issue will be covered by #26.
