### ISSUE TITLE
Constant errors on 0.6.4 with textDocument/completion failed.

### ISSUE THREAD

**Issue by icehaunter** [octref/vetur#175]
On some lines, on each edit VS Code displays this error again and again:
[Error - 6:06:35 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'parameters' of undefined
  Code: -32603 
[Error - 6:06:36 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'parameters' of undefined
  Code: -32603

**Comment by syaka-yin** [comment]
I got the same error
![bug](https://cloud.githubusercontent.com/assets/4370991/25703425/1d809e1a-3108-11e7-9885-e985ab5cd92e.png)
actually, the file `/Users/yinjun/project/card/src/components/card.vue` is exist

**Comment by ppasieka** [comment]
@syaka-yin check if in your tsconfig.json / jsconfig.json file you include vue files

https://github.com/octref/vetur#setup

https://code.visualstudio.com/docs/languages/jsconfig

**Comment by octref** [comment]
Published 0.6.5 including the fix.
