### ISSUE TITLE
Use js/ts formatting options from general config

### ISSUE THREAD

**Issue by pdanpdan** [octref/vetur#176]
In VSCode there are already settings for js/ts formatting under javascript.format.* and typescript.format.*.
Can you please use these as defaults?

```
  "typescript.format.insertSpaceAfterCommaDelimiter"
  "typescript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions"
  "typescript.format.insertSpaceAfterKeywordsInControlFlowStatements"
  "typescript.format.insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces"
  "typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets"
  "typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis"
  "typescript.format.insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces"
  "typescript.format.insertSpaceAfterSemicolonInForStatements"
  "typescript.format.insertSpaceBeforeAndAfterBinaryOperators"
  "typescript.format.placeOpenBraceOnNewLineForControlBlocks"
  "typescript.format.placeOpenBraceOnNewLineForFunctions"
```

**Comment by octref** [comment]
https://github.com/octref/vetur/blob/master/docs/formatting.md#jsts

I'd like to keep vetur's setting minimal. All these settings are set with reasonable defaults.
Which one do you want to be able to change?

**Comment by pdanpdan** [comment]
Hello.

I don't want to change any of them in vue/vetur.
I would just want vetur to respect the settings from VSCode (the ones that are already set in settings under typescript.format.* or javascript.format.*).

**Comment by octref** [comment]
That's a strange way it would work. I'm not interested in that.

If there is specific js formatting settings you'd like to be able to tweak, open a new issue.
In the long term I'm looking into adopting better formatters like https://github.com/prettier/prettier
