### ISSUE TITLE
Language server crashes because of 'Could not find file'

### ISSUE THREAD

**Issue by THaGKI9** [octref/vetur#177]
Recently I have to use some vue-like single component file, but its extension name is '.wpy' but not '.vue',
vetur works perfect for '.wpy' in the past and I don't know when it starts to crash but I just cannot use it for '.wpy' and here's is the log.

> C:\Users\Tony Ke\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:84996
>                 throw new Error("Could not find file: '" + fileName + "'.");
>                 ^
> 
> Error: Could not find file: 'c:\Users\Tony Ke\Desktop\liru\src\app.wpy'.
>     at getValidSourceFile (C:\Users\Tony Ke\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:84996:23)
>     at Object.getSyntacticDiagnostics (C:\Users\Tony Ke\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:85204:52)
>     at Object.doValidation (C:\Users\Tony Ke\.vscode\extensions\octref.vetur-0.6.4\client\server\modes\javascriptMode.js:131:49)
>     at C:\Users\Tony Ke\.vscode\extensions\octref.vetur-0.6.4\client\server\htmlServerMain.js:142:43
>     at Array.forEach (native)
>     at validateTextDocument (C:\Users\Tony Ke\.vscode\extensions\octref.vetur-0.6.4\client\server\htmlServerMain.js:140:59)
>     at Timeout._onTimeout (C:\Users\Tony Ke\.vscode\extensions\octref.vetur-0.6.4\client\server\htmlServerMain.js:134:9)
>     at tryOnTimeout (timers.js:232:11)
>     at Timer.listOnTimeout (timers.js:202:5)
> [Info  - 16:50:01] Connection to server got closed. Server will restart.

**Comment by THaGKI9** [comment]
vetur: 0.6.4
vscode: 1.11.2

**Comment by octref** [comment]
You can try adding wpy files to your jsconfig / tsconfig like this:

![image](https://cloud.githubusercontent.com/assets/4033249/25707191/c80d2b08-30b0-11e7-8550-b27f380371c3.png)

But there wpy files are not supported right now.

**Comment by THaGKI9** [comment]
Your solution doesn't work...
I know vetur does not officially support any wpy files but actually the format of wpy file is just like vue single component file[template+style+script].So I  associate *.wpy file with vue by modifying `setting.json`.

Vetur works perfect in the past but I don't remember the version. what happens to the update...

**Comment by octref** [comment]
Try downloading 0.5.6 here https://github.com/octref/vetur/issues/136#issue-223411869 and don't upgrade. I'll think about adding wpy support.
