### ISSUE TITLE
Support for Flow

### ISSUE THREAD

**Issue by chrisnicola** [octref/vetur#178]
I'm trying this out with my project which uses flow for Vue components. Currently flow is enabled by adding `// @flow` to the top of the `<script>` tag. I also use the Flow ESLint plugins so I do get flow errors/warnings through the ESLint plugin.

Unfortunately I'm also getting Javascript validation errors like:

```
'types' can only be used in a .ts file.
```

There doesn't seem to be a way to turn off Javascript validation in Vue files, or detect that Flow is being used right now.

**Comment by octref** [comment]
No specific support for flow is planned, but I'll add options to disable validation for specific regions. Tracked in #179.

**Comment by chrisnicola** [comment]
Thanks that would work perfectly. The ESLint integration for flow is sufficient for my needs for now. One advantage of supporting flow eventually might be improved completion.

**Comment by octref** [comment]
`vetur.validation.script` and `vetur.validation.style` will be available in next release.
