### ISSUE TITLE
Comment-toggling is not working

### ISSUE THREAD

**Issue by kinanson** [octref/vetur#18]
I used ctrl+/ want to annotation that is wrong for template and I key like col-md-3 when key - intellisense hide and scss is the same.
can you fix that.
thank you.

**Comment by octref** [comment]
Thanks for reporting. I'll take a look tomorrow.

**Comment by octref** [comment]
There are some changes upstream to how the formatting is handled:

https://github.com/Microsoft/vscode/commits/master/extensions/html

I want to wait a bit before doing this, as VSCode is changing its mechanism for handling comment-toggling in embedded language.

**Comment by kinanson** [comment]
I see.thank you.

**Comment by octref** [comment]
@inJonathan @kinanson I published 0.2.2 which should fix it.

Comment-toggling now should work for all supported languages:
- html/jade/pug
- css/sass/scss/less/stylus
- js/ts

**Comment by mrzzcn** [comment]
this issue is showing again: when I pressed 'Cmd + /' inside the template part, two slashes '//' show up in the start of the line.

**Comment by octref** [comment]
@mrzzcn 
![format](https://cloud.githubusercontent.com/assets/4033249/24072263/caa362e4-0bba-11e7-92db-465c83116c85.gif)
Which version are you using?

**Comment by mrzzcn** [comment]
vscode 1.10.2 & vetur 0.5.5

**Comment by mrzzcn** [comment]
something print to the console:
```bash
[Info  - 9:18:56 PM] ESLint server is running.
[Info  - 9:18:56 PM] ESLint library loaded from: /usr/local/lib/node_modules/eslint/lib/api.js
[Error - 9:18:56 PM] 
Failed to load plugin html: Cannot find module 'eslint-plugin-html'
Happend while validating /Users/zz/Desktop/test.vue
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure 'eslint-plugin-html' is installed globally as well.
3. If ESLint is installed locally, then 'eslint-plugin-html' isn't installed correctly.

Consider running eslint --debug /Users/zz/Desktop/test.vue from a terminal to obtain a trace about the configuration files used.
[Error - 9:20:09 PM] Cannot find module 'eslint-config-airbnb/base' Referenced from: /Users/zz/.eslintrc.js

```

does these mean something?

**Comment by mrzzcn** [comment]
@octref 
I think I just resolve my problem by uninstall a extension named 'Vue Component' , and then I can't search the extension again, don't what's wrong. Thank you!

**Comment by octref** [comment]
That extension is no longer maintained and unpublished by its author.
