### ISSUE TITLE
JS-IntelliSense Hover Information are gone after 0.6.5

### ISSUE THREAD

**Issue by cynecx** [octref/vetur#181]
After updating to vetur 0.6.5, type information aren't available anymore when hovered over a symbol.
This happens only in *.vue files. It worked perfectly before.

**Comment by octref** [comment]
For files not included in your jsconfig/tsconfig, vetur no longer adds IntelliSense.

See https://github.com/octref/vetur#setup

**Comment by octref** [comment]
Oops sorry I was sleepy and read it wrong.

**Comment by octref** [comment]
Try 0.6.6.

**Comment by cynecx** [comment]
@octref Thank you. It works fine now.
