### ISSUE TITLE
syntax highlighting breaks after type casting

### ISSUE THREAD

**Issue by nexus-uw** [octref/vetur#19]
![screen shot 2017-01-13 at 1 40 56 pm](https://cloud.githubusercontent.com/assets/3188890/21941292/0aa57bd6-d996-11e6-86d4-4e29ad76b999.png)

In the above screenshot, the syntax highlighting is broken after the ```<Thing>``` typecasting 

My machine
OS: macOS
VScode: 1.8.1

**Comment by octref** [comment]
`lang="ts"` is marked as js now. Thanks for reporting. I'll push a fix soon.

**Comment by octref** [comment]
I'll push 0.2.1 with the fix soon. Here is the effect.

![image](https://cloud.githubusercontent.com/assets/4033249/21974883/50b86a64-dc04-11e6-8e37-fa11427011bd.png)
