### ISSUE TITLE
Vetur can't work in a new file.

### ISSUE THREAD

**Issue by NaccOll** [octref/vetur#192]
## Env

- VSCode Version: 1.12.1
- OS Version: Windows 10 64bit
- Node Version
- Vetur Version: 0.6.8

## Problem

Vetur can't work in a new file.

## Steps to Reproduce
1. 
```shell
npm install vue-cli 
```
2.
```shell
vue init webpack test
```
3.
```shell
cd test
npm install
```
4. create a new file named Test.vue in /src/components/
```vue
<template>
  <div>test</div>
</template>

<script>
export default {
  name: 'Test'
}
</script>

<style>

</style>

```
5. IntelliSense can't work
[![https://gyazo.com/584ccd53a53737917ab12081332d4ad4](https://i.gyazo.com/584ccd53a53737917ab12081332d4ad4.png)](https://gyazo.com/584ccd53a53737917ab12081332d4ad4)

6. restart VSCode

7. This is normal
[![https://gyazo.com/93b4662a5679c14fa0443cef77c54a7e](https://i.gyazo.com/93b4662a5679c14fa0443cef77c54a7e.png)](https://gyazo.com/93b4662a5679c14fa0443cef77c54a7e)

**Comment by octref** [comment]
Good find. Thanks!

Btw, which theme are you using?

**Comment by NaccOll** [comment]
@octref 
Quiet Light

**Comment by octref** [comment]
The fix is published in 0.6.9.

**Comment by NaccOll** [comment]
@octref 
Sorry, I have to ask for your help in  Vetur 0.6.9. It work in *.js. But it is lazy in *.vue.
[![https://gyazo.com/9eb88e60c42a6b57fecabef1e3c64b34](https://i.gyazo.com/9eb88e60c42a6b57fecabef1e3c64b34.png)](https://gyazo.com/9eb88e60c42a6b57fecabef1e3c64b34)

This is similar to #183.

**Comment by NaccOll** [comment]
@octref 
More Info:
It is normal for some function such as lint, format, snippet and so on. But IntelliSense can't work.

**Comment by octref** [comment]
Is it only for new vue file or for all vue files?
Are you using cnpm and  having symlinks in your `node_modules`?
What's your `npm ls --depth=0`?

**Comment by NaccOll** [comment]
@octref 
It is for all vue files. I use npm.
```
+-- autoprefixer@6.7.7
+-- babel-core@6.24.1
+-- babel-eslint@7.2.3
+-- babel-loader@6.4.1
+-- babel-plugin-istanbul@4.1.3
+-- babel-plugin-transform-runtime@6.23.0
+-- babel-preset-env@1.4.0
+-- babel-preset-stage-2@6.24.1
+-- babel-register@6.24.1
+-- chai@3.5.0
+-- chalk@1.1.3
+-- chromedriver@2.29.0
+-- connect-history-api-fallback@1.3.0
+-- copy-webpack-plugin@4.0.1
+-- cross-env@4.0.0
+-- cross-spawn@5.1.0
+-- css-loader@0.28.1
+-- eslint@3.19.0
+-- eslint-config-standard@6.2.1
+-- eslint-friendly-formatter@2.0.7
+-- eslint-loader@1.7.1
+-- eslint-plugin-html@2.0.3
+-- eslint-plugin-promise@3.5.0
+-- eslint-plugin-standard@2.3.1
+-- eventsource-polyfill@0.9.6
+-- express@4.15.2
+-- extract-text-webpack-plugin@2.1.0
+-- file-loader@0.11.1
+-- friendly-errors-webpack-plugin@1.6.1
+-- html-webpack-plugin@2.28.0
+-- http-proxy-middleware@0.17.4
+-- inject-loader@3.0.0
+-- karma@1.7.0
+-- karma-coverage@1.1.1
+-- karma-mocha@1.3.0
+-- karma-phantomjs-launcher@1.0.4
+-- karma-phantomjs-shim@1.4.0
+-- karma-sinon-chai@1.3.1
+-- karma-sourcemap-loader@0.3.7
+-- karma-spec-reporter@0.0.30
+-- karma-webpack@2.0.3
+-- lolex@1.6.0
+-- mocha@3.3.0
+-- nightwatch@0.9.15
+-- opn@4.0.2
+-- optimize-css-assets-webpack-plugin@1.3.1
+-- ora@1.2.0
+-- phantomjs-prebuilt@2.1.14
+-- rimraf@2.6.1
+-- selenium-server@3.4.0
+-- semver@5.3.0
+-- shelljs@0.7.7
+-- sinon@2.2.0
+-- sinon-chai@2.10.0
+-- url-loader@0.5.8
+-- vue@2.3.2
+-- vue-loader@11.3.4
+-- vue-router@2.5.3
+-- vue-style-loader@2.0.5
+-- vue-template-compiler@2.3.2
+-- webpack@2.5.1
+-- webpack-bundle-analyzer@2.6.0
+-- webpack-dev-middleware@1.10.2
+-- webpack-hot-middleware@2.18.0
`-- webpack-merge@4.1.0
```

All features can work except IntelliSense. 
Perhaps, I should have a new issue.

**Comment by octref** [comment]
It seems you are using the webpack template? It's working for me fine.
Can you try removing your `node_modules` folder and run `npm i` again? The only thing I can think of is your dependency is not installed correctly.

![image](https://cloud.githubusercontent.com/assets/4033249/26090790/2413c0ec-39d5-11e7-808e-027fea96a023.png)

**Comment by NaccOll** [comment]
@octref 
It still can't work after `npm i`. I don't know the reason.
All features can work in Vetur 0.6.8. But IntelliSense is lazy in all vue files in Vetur 0.6.9.

**Comment by octref** [comment]
Try renaming the project so the cache resets...
Meanwhile if that's the cause I'll need to figure out a way to clear cache between updates.

**Comment by NaccOll** [comment]
Sorry, it is unuseful for me. In fact, the feature of IntelliSense can't work in all vue files in all project when the version of vetur is 0.6.9. Maybe, I use vetur 0.6.8 before a new version.

**Comment by octref** [comment]
I'll track that in 205.
