### ISSUE TITLE
Add grammar for html comments outside all regions.

### ISSUE THREAD

**Issue by octref** [octref/vetur#195]

**Comment by qiansen1386** [comment]
Hi folk, I am not sure whether you can read Chinese? 
我觉得这里的grammar应该是syntax。编程一般都是用syntax，指句型句法，而不涉及语态等规则。

**Comment by octref** [comment]
https://manual.macromates.com/en/language_grammars

**Comment by qiansen1386** [comment]
Yes, it's fine, but IMO not quite accurate.
`Grammar =  semantics + syntax`
Here, you are talking about html comments. It's certainly a syntax problem. There is nothing to do with semantics. 
That's a trivial issue though.

**Comment by octref** [comment]
![image](https://cloud.githubusercontent.com/assets/4033249/26027814/c51d108c-37e2-11e7-9bf7-51c4615a24f3.png)
