### ISSUE TITLE
Suggest add a settings item to allow user to disable Vue Language Server

### ISSUE THREAD

**Issue by Clarence-pan** [octref/vetur#197]
It's really annoying that `Vue Language Server` crashes every 2 to 10 minutes. 

```
vetur initialized
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
[Info  - 下午5:39:09] Connection to server got closed. Server will restart.
vetur initialized
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
[Info  - 下午5:46:38] Connection to server got closed. Server will restart.
vetur initialized

```

So, could you add a settings item to allow user to disable Vue Language Server?

**Comment by octref** [comment]
First sorry for the crashes.

Can you post your jsconfig/tsconfig if you have one for your project?
Also, do you have symlink in your `node_modules`?

**Comment by qiansen1386** [comment]
@Clarence-pan  You need to use the latest version. As long as I know, the 0.6.8 version have fixed this issue.

**Comment by octref** [comment]
@qiansen1386 Thanks for the suggestion.

@Clarence-pan Closing this issue but feel free to reopen if this happens again.

**Comment by Clarence-pan** [comment]
@qiansen1386 Thanks. I will try the latest version tomorrow.

@octref Yes, there are symlinks. Because `cnpm` is used to make module installation faster.  
But I don't have a tsconfig or jsconfig. 

May be one of the reason is my project is too big? I counted the numbers of `.vue` and `.js` files. There are total 100 `.vue` files (a coincidence) and 79 `.js` files.

Do you have tested `vetur` on a such big project? 

I'm sorry but I cannot provide the source codes - as they owned by our company.

**Comment by octref** [comment]
@Clarence-pan I've tested it on large project and it works fine. What doesn't work now is symlink, https://github.com/octref/vetur/issues/193

I realize a lot of people in China are using cnpm and it uses symlink by default. I'll try to fix it.

**Comment by Clarence-pan** [comment]
@octref Well. I'll try to use npm directly tomorrow. Thanks.

**Comment by octref** [comment]
@Clarence-pan Try to use yarn which doesn't symlink. It also caches download so you don't have to download the same package twice (I know connection from China to NPM can be slow),

**Comment by Clarence-pan** [comment]
@octref  Besiding resolving the issue of crashes, I still suggest you to add a settings item to allow users to disable `Vue Language Server`.  Is there a way to stop `Vue Language Server`?

**Comment by octref** [comment]
Without the language server many features would not work. 

0.5.6 is the last release without language server, install instruction here: https://github.com/octref/vetur/issues/136#issue-223411869

**Comment by Clarence-pan** [comment]
@octref OK. Thanks. I should have realized it - like Windows cannot remove IE. 
I will try <https://github.com/octref/vetur/issues/136#issue-223411869> if it still keeps crashing.
