### ISSUE TITLE
Follow [optionally] atom-beautify's approach when formatting <template> section in .vue files

### ISSUE THREAD

**Issue by lbssousa** [octref/vetur#198]
Is it possible to make .vue file formatting behave closer to [atom-beautify](https://github.com/Glavin001/atom-beautify)'s approach for `<template>` section? In that context, the very first `<template></template>`, `<script></script>`, and `<style></style>` pairs of tags in .vue files are treated as a kind of "section identifier", so that their inner contents are never indented relatively to them. Example:

```
<template>
<div> <-- this line is NOT indented
  (...) <-- inner contents are indented as usual
</div>
</template>

<script>
let var1 = 'foo' <-- this line is NOT indented

export default {
  (...) <-- inner contents are indented as usual
}
</script>

<style>
.foo { <-- this line is NOT indented
  display: inline; <-- inner contents are indented as usual
  (...)
}
</style>
```
Current VSCode/Vetur formatter works the same way for .vue files, except for `<template>` section (it **does** indent its first child). Would it be possible to add an option to Vetur to prevent it from indenting `<template>`'s first child, as atom-beautify does?

**Comment by octref** [comment]
I won't add setting for not indenting `<template>`, but I'll add options so you can choose to have initial indent or not for `<script>` and `<style>`.

Just take a look at official vue examples. It's idiomatic to indent `<template>` but not others:

https://github.com/vuejs/vuex/blob/dev/examples/chat/components/App.vue
