### ISSUE TITLE
Implement language server

### ISSUE THREAD

**Issue by octref** [octref/vetur#2]
- [x] Use https://github.com/Microsoft/vscode-languageserver-node-example as a base
- [x] Update deps to use `TS^2.0.3`
- [x] Move `/extensions/html` to node example

**Comment by stackia** [comment]
非常期待！

**Comment by octref** [comment]
Related upstream issue: https://github.com/Microsoft/vscode/issues/15377

**Comment by octref** [comment]
Released 0.2 which adapted VSCode's html extension into a language server for Vue.

IntelliSense is now available to html/css/js/scss/less.

**Comment by yeluoqiuzhi** [comment]
How about ts in <script lang="typescript">?

**Comment by octref** [comment]
@yeluoqiuzhi I don't think there is a standard way yet to use TS with Vue Single File Component.

**Comment by yeluoqiuzhi** [comment]
yeah, so that we use seperated file, instead of Single file Component.
Just like [vue-class-component](https://github.com/vuejs/vue-class-component)

**Comment by octref** [comment]
Aren't that just a TS file, where you don't even need `<script lang="typescript">`?

**Comment by yeluoqiuzhi** [comment]
I want to write typescript in a Single File Component. Just use [vue-ts-loader](https://github.com/HerringtonDarkholme/vue-ts-loader)

**Comment by octref** [comment]
I want to build better support for html/js/css/scss first, as these are the most popular ones.

The project you pointed to seems experimental. I won't spend time building support for it unless it gains traction.

**Comment by octref** [comment]
@yeluoqiuzhi TS syntax highlighting is added, see #19. I'll see if I can do intelliSense later.
