### ISSUE TITLE
Use pugbeautify for formatting when lang=pug/jade

### ISSUE THREAD

**Issue by sudo-suhas** [octref/vetur#20]
Visual Studio Code version - 1.8.1
Platform - Windows 8
Vetur version - 0.2.0
Pug beautify version - 1.0.2

Format document option works fine for plain HTML but if I am trying to use `lang="pug"` for template, it garbles the template.

Before:
```
<template lang="pug">
    .hello
        h1 {{ msg }}
        h2 Essential Links
        ul
            li: a(href='https://vuejs.org', target='_blank') Core Docs
            li: a(href='https://forum.vuejs.org', target='_blank') Forum
            li: a(href='https://gitter.im/vuejs/vue', target='_blank') Gitter Chat
            li: a(href='https://twitter.com/vuejs', target='_blank') Twitter
            br
            li: a(href='http://vuejs-templates.github.io/webpack/', target='_blank') Docs for This Template
        h2 Ecosystem
        ul
            li: a(href='http://router.vuejs.org/', target='_blank') vue-router
            li: a(href='http://vuex.vuejs.org/', target='_blank') vuex
            li: a(href='http://vue-loader.vuejs.org/', target='_blank') vue-loader
            li: a(href='https://github.com/vuejs/awesome-vue', target='_blank') awesome-vue
</template>
```

After:
```
<template lang="pug">
    .hello h1 {{ msg }} h2 Essential Links ul li: a(href='https://vuejs.org', target='_blank') Core Docs li: a(href='https://forum.vuejs.org',
    target='_blank') Forum li: a(href='https://gitter.im/vuejs/vue', target='_blank') Gitter Chat li: a(href='https://twitter.com/vuejs',
    target='_blank') Twitter br li: a(href='http://vuejs-templates.github.io/webpack/', target='_blank') Docs for This Template
    h2 Ecosystem ul li: a(href='http://router.vuejs.org/', target='_blank') vue-router li: a(href='http://vuex.vuejs.org/',
    target='_blank') vuex li: a(href='http://vue-loader.vuejs.org/', target='_blank') vue-loader li: a(href='https://github.com/vuejs/awesome-vue',
    target='_blank') awesome-vue
</template>
```

I have installed pugbeautify but am not able to figure out how to delegate the document format to pugbeautify from .vue files.

**Comment by octref** [comment]
Thanks for reporting, embedded formatter isn't supported yet.
I'll take a look after doing embedded error checking.

**Comment by sudo-suhas** [comment]
Thanks. Much appreciated. :)

**Comment by octref** [comment]
OK, just an update, as people seem to want this feature.

VSCode doesn't seem to be interested in including formatters in the core, and encourages extensions to provide formatting support: https://github.com/Microsoft/vscode/issues/19166

I can try to add setting for external formatters per language, but it's not on the top of my list. I added it to the roadmap.

Meanwhile, VSCode includes html / js formatter, so you can still select that region and "Format Selection".

PR is welcome.

**Comment by sudo-suhas** [comment]
To add to that, I was also able to use jsbeautify for the Vue files.. That works well with html, js and css.

**Comment by ripper234** [comment]
Same for me on `LESS` style sections - formatter doesn't do anything on these sections.
(FYI without vetur installed, formatting works well, but syntax highlighting doesn't and there are incorrect warnings)

**Comment by octref** [comment]
@ripper234 LESS formatting is now fixed.

For this issue, probably need to include https://github.com/mrmlnc/vscode-pugbeautify as a dependency. I'll look into that for 0.5.

**Comment by octref** [comment]
Note to myself: Disable pug and sass region formatting for now for #68. Look into pugbeautify later.

**Comment by octref** [comment]
Closing in favor of #82.
