### ISSUE TITLE
The extension is not easily discoverable when searching for a vue extension

### ISSUE THREAD

**Issue by egamma** [octref/vetur#202]
This is what is shown in the market place.
![image](https://cloud.githubusercontent.com/assets/172399/26035185/952be06a-38c8-11e7-9406-18d9d015a77f.png)

Suggest to include 'vue' in the `displayName` of the extension.

**Comment by octref** [comment]
I think you are searching inside VS marketplace instead of VSCode!

Sorting of extensions is tracked by: https://github.com/Microsoft/vscode/issues/24511

**Comment by egamma** [comment]
@octref oops... you are correct, but you see I really care :smile:.
