### ISSUE TITLE
HTML Tag Matching doesn't work in Vue file !

### ISSUE THREAD

**Issue by zuibunan** [octref/vetur#204]
In  HTML file, click HTML tag ,
![image](https://cloud.githubusercontent.com/assets/3386786/26048349/505304a2-3989-11e7-8974-46e47d6d52ad.png)

In Vue file, click HTML tag, all tags are selected with highlight !
![image](https://cloud.githubusercontent.com/assets/3386786/26048401/85b7d474-3989-11e7-8750-65bcd842ebc5.png)

**Comment by octref** [comment]
Dup of #194.

**Comment by davidsielert** [comment]
This is still not working for me..

**Comment by ccqgithub** [comment]
This is still not working for me..

**Comment by ccqgithub** [comment]
@octref  The problem still exists if i add `lang` attribute like this:
```
<template lang="html">
```

**Comment by octref** [comment]
Found the bug.
