### ISSUE TITLE
Vetur 0.6.9 - No intelliSense or hover-to-show-type in *.vue files

### ISSUE THREAD

**Issue by dannief** [octref/vetur#205]
Vetur 0.6.9
VSCode 1.12.2
Node 7.4.0

Vetur is the only vue extension installed.

I have a vue-typescript project. My tsconfig.json is

```
{
  "compilerOptions": {
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "lib": [
      "dom",
      "es2015",
      "es2015.promise"
    ],
    "types": [
      "vue-typescript-import-dts"
    ],
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "strict": true
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.vue",
    "custom.d.ts"
  ],
  "compileOnSave": false
}

```

There does not seem to be any intelliSense or hover working on the script blocks. I have seen issue #191, but I am not getting an error in the Vue Language Server output. It simply says "vetur initialized" 

As suggested in the readme, i cloned the https://github.com/vuejs/vue-hackernews-2.0 project but it does not work in this project either.  I then added a jsconfig.json with the following content, but that did not help.

```
{
  "include": [
      "src/**/*"
  ]
}
```

I apologize If I have missed something in the setup, but I cannot think what that would be.

Thanks.

**Comment by octref** [comment]
You need to install the dependencies (especially vue/vuex/vue-router), like `npm i`, before IntelliSense would work.

However, if that doesn't work, can you try to install this version:
(Instruction: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix)

[vetur-0.6.9.vsix.zip](https://github.com/octref/vetur/files/1004595/vetur-0.6.9.vsix.zip)

Then go to the file, try IntelliSense, and let me know the output?

**Comment by dannief** [comment]
This is the output from the extension. (I typed `[].` The expectation was to get a list of array functions.)

```
vetur initialized
file:///c%3A/Dev/Code_Samples/temp/src/views/ItemList.vue
c:/Dev/Code_Samples/temp/src/app.js,c:/Dev/Code_Samples/temp/src/App.vue,c:/Dev/Code_Samples/temp/src/entry-client.js,c:/Dev/Code_Samples/temp/src/entry-server.js,c:/Dev/Code_Samples/temp/src/api/create-api-client.js,c:/Dev/Code_Samples/temp/src/api/create-api-server.js,c:/Dev/Code_Samples/temp/src/api/index.js,c:\Dev\Code_Samples\temp\src\components\Comment.vue,c:/Dev/Code_Samples/temp/src/components/Item.vue,c:/Dev/Code_Samples/temp/src/components/ProgressBar.vue,c:\Dev\Code_Samples\temp\src\components\Spinner.vue,c:/Dev/Code_Samples/temp/src/router/index.js,c:/Dev/Code_Samples/temp/src/store/actions.js,c:/Dev/Code_Samples/temp/src/store/getters.js,c:/Dev/Code_Samples/temp/src/store/index.js,c:/Dev/Code_Samples/temp/src/store/mutations.js,c:/Dev/Code_Samples/temp/src/util/filters.js,c:/Dev/Code_Samples/temp/src/util/title.js,c:/Dev/Code_Samples/temp/src/views/CreateListView.js,c:\Dev\Code_Samples\temp\src\views\ItemList.vue,c:/Dev/Code_Samples/temp/src/views/ItemView.vue,c:/Dev/Code_Samples/temp/src/views/UserView.vue
```

**Comment by octref** [comment]
Oops Windows path problem. Thanks a lot now I see exactly where is the bug.

**Comment by jamesxv7** [comment]
Same error here, glad to help with the testing, I'm using Windows env too.

**Comment by octref** [comment]
Studying for a final tomorrow but I'll fix this asap.

**Comment by yanhuayu** [comment]
Same error here  win10
0.6.10 just show vetur initialized
0.6.9 :
`vetur initialized
file:///f%3A/youloft_git/WebApp/wnl_discovery_tab/src/App.vue
f:/youloft_git/WebApp/wnl_discovery_tab/src/main.js,f:/youloft_git/WebApp/wnl_discovery_tab/src/plugins/util.js,f:/youloft_git/WebApp/wnl_discovery_tab/src/plugins/hscroll/core.js,f:/youloft_git/WebApp/wnl_discovery_tab/src/plugins/hscroll/index.js,f:/youloft_git/WebApp/wnl_discovery_tab/src/plugins/hscroll/render.js,f:/youloft_git/WebApp/wnl_discovery_tab/src/plugins/vscroll/core.js,f:/youloft_git/WebApp/wnl_discovery_tab/src/plugins/vscroll/index.js,f:/youloft_git/WebApp/wnl_discovery_tab/src/plugins/vscroll/render.js,f:/youloft_git/WebApp/wnl_discovery_tab/src/store/index.js,f:/youloft_git/WebApp/wnl_discovery_tab/src/store/modules/business.js,f:/youloft_git/WebApp/wnl_discovery_tab/src/store/modules/user.js,f:\youloft_git\WebApp\wnl_discovery_tab\src\App.vue,f:/youloft_git/WebApp/wnl_discovery_tab/src/plugins/hscroll/hscroll.vue,f:/youloft_git/WebApp/wnl_discovery_tab/src/plugins/spinner/spinner.vue,f:/youloft_git/WebApp/wnl_discovery_tab/src/plugins/vscroll/vscroll.vue`

**Comment by octref** [comment]
Sorry haven't had access to a Windows machine so this took longer to fix. This is fixed and I'll publish a new release tonight.

**Comment by jamesxv7** [comment]
Already update it! Stay tune for feedback.
