### ISSUE TITLE
v-else, v-cloak, v-once expect no expression

### ISSUE THREAD

**Issue by Moerj** [octref/vetur#208]
![qq20170516-212858 2x](https://cloud.githubusercontent.com/assets/13795438/26108566/7ac4c210-3a7f-11e7-916f-bda8d27ed7cb.jpg)

![qq20170516-212919 2x](https://cloud.githubusercontent.com/assets/13795438/26108577/8313c9ac-3a7f-11e7-915a-58753df3187b.jpg)

![qq20170516-212930 2x](https://cloud.githubusercontent.com/assets/13795438/26108584/89c0acd4-3a7f-11e7-8e2e-2439766045f6.jpg)

Write velse it generate v-else="". I Should be v-else

**Comment by octref** [comment]
Good catch. I'll fix that for v-cloak and v-once too.
