### ISSUE TITLE
vue scss no work

### ISSUE THREAD

**Issue by AimLuo** [octref/vetur#21]
Disabled vue-snippets，by HTML：
![image](https://cloud.githubusercontent.com/assets/21124342/21976191/9e4c94e2-dc0b-11e6-9d3e-b4b120a1370c.png)
Enabled vue-snippets，by HTML:
![image](https://cloud.githubusercontent.com/assets/21124342/21976230/d318d636-dc0b-11e6-9d8c-482846357609.png)
Enabled vue-snippets，by Vue：
![image](https://cloud.githubusercontent.com/assets/21124342/21976818/9950a7b4-dc0e-11e6-9699-3eb9434e2f00.png)

**Comment by octref** [comment]
You need to have
```
"files.associations": {
  "*.vue": "vue"
}
```
in your user settings to use Vue syntax for .vue files.

What do you want for last image? Is `b1-solid-red` a class and you want emmet for it?

**Comment by AimLuo** [comment]
I have added:
"files.associations": {
  "*.vue": "vue"
}
Syntax highlighting is working.
**YES!!!!  I NEED EMMET**

**Comment by octref** [comment]
You can track emmet support in #14.

**Comment by AimLuo** [comment]
thanks! I'll track at any time.

**Comment by AimLuo** [comment]
don't add:
`"files.associations": {
  "*.vue": "vue"
}
 `
we can open vue file by html, and make Syntax highlighting in `<style lang=scss></style>`

**Comment by octref** [comment]
> don't add:
"files.associations": { "*.vue": "vue" }
we can open vue file by html, and make Syntax highlighting in <style lang=scss></style>

No you can't. The extension Vue 2 Snippet doesn't support scss correctly I think. You need to disable it and add the file associations.
