### ISSUE TITLE
could not format correctly

### ISSUE THREAD

**Issue by flyher** [octref/vetur#214]
Other extensions have been disabled, after format code , can not pass eslint detection.

![11](https://cloud.githubusercontent.com/assets/5570324/26347284/a7932d48-3fdb-11e7-879a-cd16e266ee7f.png)

![2222](https://cloud.githubusercontent.com/assets/5570324/26346766/d5198728-3fd9-11e7-92a7-9522c4f150c1.png)

**Comment by ppasieka** [comment]
in VS Code you can change formatter settings (User settings or workspace settings)

![image](https://cloud.githubusercontent.com/assets/2170707/26350632/2b3759a8-3fb4-11e7-87c2-9d4059e32523.png)

**Comment by flyher** [comment]
@ppasieka 
Thank you for you suggestion, i will try it tomorrow!

**Comment by flyher** [comment]
@ppasieka
Hi , i checked my VS Code, the default setting is:
```json
"vetur.format.js.InsertSpaceBeforeFunctionParenthesis": false
```
i disabled all other extensions again, and restart the VS Code, it still format wrong.

my VS Code version: 1.12.2 and vetur version: 0.6.10

**Comment by octref** [comment]
> "vetur.format.js.InsertSpaceBeforeFunctionParenthesis": false

Do you mean you have it as true or false?
You need it to be true to have the space before function paren.

**Comment by flyher** [comment]
@octref
Oh, aha, it's my mistake.
Thank you very much~~~
