### ISSUE TITLE
Request textDocument/documentHighlight failed. (0.6.10)

### ISSUE THREAD

**Issue by yinheli** [octref/vetur#215]
```
vetur version: 0.6.10
vscode version: 1.12.2
```

```
vetur initialized
[Error - 2:16:33 AM] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: Debug Failure. False expression: 
  Code: -32603 
```

**Comment by Christilut** [comment]
Same here:
```
[Error - 1:31:35 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'parameters' of undefined
  Code: -32603 
[Error - 1:32:03 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'parameters' of undefined
  Code: -32603 
```

**Comment by skycult** [comment]
This plugin is now very unstable.

**Comment by octref** [comment]
@yinheli 

DocumentHighlight is for highlighting areas related to the object under current cursor.

![image](https://cloud.githubusercontent.com/assets/4033249/26554351/a63a5418-445d-11e7-8da6-8342b181ce0d.png)

Is this feature working for you?
If not, when vetur is showing this error, which part (html/css/js) are you doing the highlighting on?

**Comment by yinheli** [comment]
@octref 

it works for stand html tags, but not working for custom components tag

versions:
```
OS: windows 10
VSCode: 1.12.2
vetur: 0.6.10
```

stand tags
![image](https://cloud.githubusercontent.com/assets/235094/26667721/2072dcfa-46d9-11e7-87c8-8f73bbdadfbd.png)

custom component tag
![image](https://cloud.githubusercontent.com/assets/235094/26667749/48701a4c-46d9-11e7-90af-d3eedb937871.png)


`documentHighlight failed` error message does not appear in windows. I reported this issues while using macOS.

Thanks.

**Comment by octref** [comment]
I'm on mac but I don't see any error messages...
![image](https://cloud.githubusercontent.com/assets/4033249/26688623/2d8aba9c-46c1-11e7-853e-6aab22d4a1b2.png)

But I can fix the highlight for custom compoennts.

**Comment by yinheli** [comment]
@octref  Thanks

It is ok now, maybe there is some conflict with other extension

![image](https://cloud.githubusercontent.com/assets/235094/26688907/8ae23c78-4726-11e7-8e35-d311b7c29fd7.png)

**Comment by yinheli** [comment]
double click, issue occurred

![sample](https://cloud.githubusercontent.com/assets/235094/26690365/98ec4282-472b-11e7-859f-790aedc14754.gif)

**Comment by octref** [comment]
Nice - I get it reproduced. Will be able to resolve it soon.

**Comment by octref** [comment]
I disabled highlight for js/ts now. Will re-enable it once the module resolution for importing vue files are resolved.
Also need to do: Fix highlighting for html tags using custom elements.

**Comment by yinheli** [comment]
@octref thanks ~ awesome extenstion

**Comment by HerringtonDarkholme** [comment]
Is this still valid? I cannot reproduce and highlight seems to work fine.

**Comment by octref** [comment]
@HerringtonDarkholme I don't think this applies anymore.

Others, open a new issue if you have this issue in latest.
