### ISSUE TITLE
I can't get script of intellisense

### ISSUE THREAD

**Issue by kinanson** [octref/vetur#217]
I don't know why.But I can't get intellisense again.I remember this was ok.Can somebody tell me how to resolve this?
![1](https://cloud.githubusercontent.com/assets/5998113/26614077/ad948c9e-45f0-11e7-8c32-0a7fa822284b.gif)

**Comment by octref** [comment]
First, do you have `vue` installed as a dependency?
Second, do you mind showing me the file explorer so I can know how you are structuring your project? (Like so)

![image](https://cloud.githubusercontent.com/assets/4033249/26688426/94251dde-46c0-11e7-82f6-39767ed70d24.png)

**Comment by kinanson** [comment]
I new cli webpack project.I also can't get intellisense.detail see below
![image](https://cloud.githubusercontent.com/assets/5998113/26704846/76f03fa6-4764-11e7-949c-04544b86bbc1.png)

![1](https://cloud.githubusercontent.com/assets/5998113/26704851/8994a700-4764-11e7-951e-c29a435c2283.gif)

**Comment by octref** [comment]
Please remove `@types/vue` from your dependency. Types are included in `vue` already and I think it's the extra typing that's messing up IntelliSense.

**Comment by kinanson** [comment]
I update to 0.6.11 and get intellisense.thank you a lot

**Comment by octref** [comment]
Oh OK maybe you are on Windows and it was broken on 0.6.10.
