### ISSUE TITLE
wrongly triggering snippets in < script lang="coffee"> blocks

### ISSUE THREAD

**Issue by beeplin** [octref/vetur#219]
The README says:

```
IntelliSense such as scaffold, template with pug, style with scss outside all language regions
```
But it seems problematic to judge if it is **outside all lauguage regions**, since in < script lang='coffee'> blocks it frequently triggers this snippets:

![image](https://cloud.githubusercontent.com/assets/13058150/26663219/de7089fa-46bb-11e7-9b5b-5e026c85eb19.png)

**Comment by octref** [comment]
![image](https://cloud.githubusercontent.com/assets/4033249/26748336/b6d75a1c-47ca-11e7-9c24-437ca36b1ffe.png)

Will be published in new version soon.
