### ISSUE TITLE
Server initialization failed

### ISSUE THREAD

**Issue by tancw** [octref/vetur#220]
Following the instructions, I completed the configuration. When I try to create my Vue file， the error occurred.

![Markdown](http://i1.piimg.com/594495/da8813fcef1e7c27.jpg)

**Comment by octref** [comment]
You need to save that file as a .vue file in disk -- What's the problem with "Untitled-1" and why it's showing a vue icon?

**Comment by tancw** [comment]
Yes, I have saved the file as a .vue file in disk. I installed the ‘vscode-icon’ extension and it can automatically detect my file type. 

I renamed the file but this error still occured.

Maybe it have a conflict with my other developments?

![Markdown](http://i1.piimg.com/594495/c4b6adf80301fb03.jpg)

**Comment by octref** [comment]
So you are opening a single vue file without a workspace? That's probably #160, which is fixed in master and will be published soon.

**Comment by tancw** [comment]
OK, I see.  I'm a beginner at vue, so I just implement some simple examples in vue document.
