### ISSUE TITLE
Style attribute has no suggest in .vue files

### ISSUE THREAD

**Issue by Moerj** [octref/vetur#223]
![qq20170605-021337 2x](https://cloud.githubusercontent.com/assets/13795438/26764193/131a14f6-4995-11e7-96c3-d20ccf97f2a7.jpg)
![qq20170605-021501 2x](https://cloud.githubusercontent.com/assets/13795438/26764194/136f7608-4995-11e7-9559-968c529ccbef.jpg)

As the picture. Vue files has no suggest. But HTML files has.

Version: Vetur 0.7.0
OS: macOS

**Comment by HerringtonDarkholme** [comment]
Technically this requires nested region detection. In the original html lang service, the root region is html so style attribute is a standalone region, no nesting.

@octref  What's your opinion? IMHO, inline style attribute shouldn't be recommended.

**Comment by octref** [comment]
I agree. Inline styles are rarely used with Vue.
With scoped styles you shouldn't need them. There are also classes to help. Finally if you really need inline styles you don't need auto completion for that one or two styles, I think.

Doing this would increase the region handling a lot, so no.

**Comment by snoopy83101** [comment]
1. When tr in a table's header sets the width
2. When setting heigth for some elements
3. When debugging styles temporarily in the development environment

I think this may still be necessary.
