### ISSUE TITLE
use Dynamic import show error

### ISSUE THREAD

**Issue by PanJiaChen** [octref/vetur#228]
![image](https://user-images.githubusercontent.com/8121621/26919487-7aa26bac-4c68-11e7-867d-2765248a69c3.png)

use Dynamic import: import() ,show error `(method) import(): any`
but in js.file  is fine

**Comment by octref** [comment]
```json
  "vetur.validation.script": false
```

Since you are using a non standard version of JS (afaik this is not in ES6 or ES7 yet).

**Comment by PanJiaChen** [comment]
thx
