### ISSUE TITLE
High CPU and memory leak

### ISSUE THREAD

**Issue by leaves4j** [octref/vetur#229]
- Platform: macOS
- Vetur version: 0.7.0
- VSCode version: 1.13.0 

I find this plugin caused the cpu and memory usage highly when update to vscode 1.13, if disable this plugin, the cpu and memory is normal
```
PID    COMMAND      %CPU      TIME     #TH   #WQ  #PORT MEM    PURG   CMPRS  PGRP  PPID  STATE    BOOSTS 
29226  Code Helper  97.1  00:25.06     9/1   1    59    1350M+ 0B     0B     28099 29179 running  *0[1]
```

**Comment by octref** [comment]
Did you try this?

![image](https://user-images.githubusercontent.com/4033249/26962817-7b2d27f4-4cf1-11e7-847f-6fad0ceb7209.png)

Also see https://github.com/octref/vetur/issues/216#issuecomment-305660816

**Comment by leaves4j** [comment]
@octref There is no `jsconfig.json` or `tsconfig.json` in my project

**Comment by octref** [comment]
Then make a `jsconfig.json` like 

```json
  {
    "include": [
      "./src/**/*"
    ]
  }
```

Only include files that's related to vue or your client side app.

**Comment by leaves4j** [comment]
@octref It's fine with `jsconfig.json` only include vue files, but It's still use memory highly when I include other js file. There is no problem in vs code 1.12 without `jsconfig.json`

**Comment by octref** [comment]
I'm assuming this worked for you. If not feel free to reopen.
