### ISSUE TITLE
ESLint stopped working - how to fix

### ISSUE THREAD

**Issue by jeromu** [octref/vetur#24]
Hi,

Please add the following to the readme, as it affects users installing this extension who also uses ESLint.

After installing vetur, your .vue files will be mapped to 'vue' type in VSCode, which will break the eslint validation that you may already have for HTML files.

To fix that, add "vue" to the list of types to validate in your settings.json file:

```
"eslint.validate": [
    "javascript",
    "javascriptreact",
    "html",
    "vue"
  ],
```

Thanks

**Comment by octref** [comment]
I think it's fine. vue files aren't natively supported in VSCode. Marking it as html to have validation isn't right in the first place.

**Comment by octref** [comment]
Actually you are right, sorry.

Seems most people are using ESlint for Vue files, so I'll add that to description.
Once I get linting for html/scss/less/css I'll push 0.3 and include a guide to configure linting.

**Comment by blake-newman** [comment]
If you are using eslint extension there is now option to enable eslint of languages. 

```json
  {
      "files.associations": {
          "*.vue": "vue"
      }, 
      "eslint.validate": ["javascript", "javascriptreact", "html", "vue"]
  }
```
Release notes: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

Note if you are using newly updated `eslint-html-plugin` you will be able to autofix vue files aswell. 
https://www.npmjs.com/package/eslint-plugin-html

**Comment by octref** [comment]
@blake-newman 

Thanks for bringing `eslint-plugin-html` up. `vetur` also splits the vue file into different regions. As ESLint is working for linting the js region, I'll work on getting validation for other regions.

**Comment by octref** [comment]
Added ESLint part to readme. Also can error-check css/scss/less now in 0.3.
