### ISSUE TITLE
Wrong syntax color on SCSS "cursor" property within Vue single file component

### ISSUE THREAD

**Issue by patoezequiel** [octref/vetur#242]
- Platform: Windows 10
- Vetur version: 0.7.0
- VSCode version: 1.13.1

As I wrote in the title of the issue, the `cursor` property is not being correctly colored inside a SCSS style tag of a Vue single file component. It is actually being colored as if it were a selector, as you can see in the screenshot below.

![image](https://user-images.githubusercontent.com/5291103/27367120-1769043e-5621-11e7-8e3d-bc011d0f8895.png)

If you want to reproduce the issue, simply allow the Vetur extension with the same version as me (0.7.0; latest version at the moment of this issue) and create a `.vue` file and paste the following code:

```
<style lang="scss">
	.selector {
		align-self: auto;
		cursor: auto;
		margin: auto;
	}
</style>
```

The expected behavior is to have all three properties: `align-self`, `cursor`, and `margin`, being colored like properties. Instead, the `cursor` property is treated as a selector, as you can see in the screenshot below.

![image](https://user-images.githubusercontent.com/5291103/27367325-8b529030-5622-11e7-8244-99bee6a8a878.png)

Moreover, the TM scope inspector in VS Code shows the grammatical difference between the correctly identified properties and the `cursor` property, as the pictures below illustrate.

![image](https://user-images.githubusercontent.com/5291103/27367682-e72a15ac-5624-11e7-8b61-bcaaa5ba7133.png)
![image](https://user-images.githubusercontent.com/5291103/27367691-f2cd5996-5624-11e7-8dd7-45212526e151.png)

The normal properties have the following tags:

- support.type.property-name.css
- meta.property-name.scss
- meta.property-list.scss
- meta.property-list.scss
- meta.property-list.scss
- source.css.scss
- source.vue

while the ´cursor´ property has these:

- entity.name.tag.css
- meta.property-list.scss
- meta.property-list.scss
- meta.property-list.scss
- source.css.scss
- source.vue

**Comment by patoezequiel** [comment]
Well, after some more testing it seems to be a problem in the syntax of the built-in Sass highlighting, not of Vetur.

**Comment by octref** [comment]
The file is at https://github.com/Microsoft/vscode/blob/master/extensions/scss/syntaxes/scss.json

> "This file has been converted from https://github.com/atom/language-sass/blob/master/grammars/scss.cson",
		"If you want to provide a fix or improvement, please create a pull request against the original repository.",

So maybe open an issue at the Atom repo.
I might have time to fix the grammar later, but now I need to focus on preparing VueConf.
