### ISSUE TITLE
Vetur plugins auto delete a space after the operator.

### ISSUE THREAD

**Issue by tangbc** [octref/vetur#244]
- Platform: macOS
- Vetur version: 0.7.0 | 2017-06-01
- VSCode version: 1.13.1 (1.13.1)

Hi, I meet an unfriendly problem that when I start a newline and typing a function name, and select it by press enter, then editor will delete the space after `=`:  

<img src="https://tangbc.github.io/others/vscode-vetur-error.gif" />

And I try to disable `vetur` plugin, this problem is not appear again.

Looking forward to solving this problem ~

**Comment by tangbc** [comment]
Supplement: it just appear when edit a `.vue` file.

**Comment by xiguaxigua** [comment]
I have also encountered this problem.

**Comment by octref** [comment]
I can confirm it.

**Comment by octref** [comment]
The problem is we have `=` as trigger for IntelliSense. I guess this was mainly for html attributes because Vetur was based on VSCode's html extension, but it doesn't make sense for vue.

The fix will be available in the next release.

**Comment by tangbc** [comment]
@octref This problem with `=` is ok in version `0.8.6` , but  I found the other problem case by `:` in object. 

It looks like:

<img src="https://tangbc.github.io/others/vscode-vetur-error-key.gif" />

**Comment by xiguaxigua** [comment]
The same bug will also be triggered by `<` and '/'
