### ISSUE TITLE
Self-closing tags error

### ISSUE THREAD

**Issue by alexsasharegan** [octref/vetur#257]
- Platform: Mac OS X El Capitan 10.11.6
- Vetur version: 0.8.2
- VSCode version: 1.13.1

# Error: Self-Closing Tags
While self-closing tags are not valid for in-dom templates, the vue-loader that parses `.vue` files into render functions can handle self-closing tags in v2. See this comment in the vue issues: https://github.com/vuejs/vue/issues/1036#issuecomment-266756591

## Expected
I think a nice aesthetic around this environment specific error is to make it a configuration option. Another option would be to ignore this error in `.vue` files.

![image](https://user-images.githubusercontent.com/16269252/27444438-3ae2f3ce-572b-11e7-8438-7ec19772b1b8.png)
![image](https://user-images.githubusercontent.com/16269252/27444506-69843864-572b-11e7-8618-5681f47c5817.png)

**Comment by SharpSeeEr** [comment]
I am also getting the error on valid self closing tags like `<img />` and `<br />`.
![image](https://user-images.githubusercontent.com/4459909/27445356-adb08bcc-5736-11e7-9622-c63870676b2c.png)

**Comment by octref** [comment]
We are incorporating https://github.com/vuejs/eslint-plugin-vue now and this comes from its rule:

https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/html-no-self-closing.md

So create a `.eslintrc` to disable it.
I'll add `vetur.validation.template` in the next version to disable html validation totally.

**Comment by alexsasharegan** [comment]
Took me a few tries to figure out how to write the rule, so for posterity, this worked for me:

```json
{
    "plugins": [
        "vue"
    ],
    "rules": {
        "vue/html-no-self-closing": "ignore"
    }
}

```

**Comment by alexsasharegan** [comment]
Hmm... on second thought, it does eventually trigger an error. Any tips @octref ?

**Comment by octref** [comment]
Yeah, but now you have fine-control over all the rules that eslint-plugin-vue@beta provides!

**Comment by alexsasharegan** [comment]
Maybe this is an issue between my local packages and my vscode extension deps?

**Comment by octref** [comment]
> it does eventually trigger an error

So VSCode still shows an error?

**Comment by alexsasharegan** [comment]
Correct. It just took a while to parse through and highlight things. The local project has this dep: `"eslint-plugin-vue": "^2.1.0",`

**Comment by alexsasharegan** [comment]
Maybe I need to set up a global `.eslintrc`? I'm a little new to using linting, and I've only got it set up for this repo right now.

**Comment by octref** [comment]
Currently we have the template checking on by default using `eslint-plugin-vue` > 3.0. But it's unconfigurable. I'll add an option to disable it.

Meanwhile with VSCode's ESLint plugin and dependency / eslintrc correctly setup, you should also be able to template linting and have fine control over the rules with .eslintrc.

**Comment by alexsasharegan** [comment]
Cool—the usual css-esque config cascade. Do you see anything wrong with what I'm doing then? I'm not entirely sure why I can't tap into the suite of vue lint rules.

**Comment by alexsasharegan** [comment]
Two possibly useful threads:
- https://github.com/vuejs/eslint-plugin-vue/issues/31#issuecomment-309206894
- https://github.com/vuejs/eslint-plugin-vue/issues/29

**Comment by alexsasharegan** [comment]
This is still not fixed for me.

**Comment by octref** [comment]
Because we haven't released the new change yet?

**Comment by alexsasharegan** [comment]
I'm not really sure. I've tried quite a few configurations, and tried to hunt down some info, but I'm running out of ideas.

**Comment by octref** [comment]
Upgrade to 0.8.3 and set `"vetur.validation.template": false` in VSCode setting.

**Comment by alexsasharegan** [comment]
Awesome! This works. 👍  I'm still confused why I can't get the vue eslint rule working.

**Comment by CalebKester** [comment]
Thanks for adding that template false. I'm with @alexsasharegan that I'd like to get the vue eslint rules working too but until I can customize them I'll just live with disabling all of them.

**Comment by octref** [comment]
You can customize them: https://octref.github.io/vetur/linting-error.html
