### ISSUE TITLE
v-for and a tag issue

### ISSUE THREAD

**Issue by yunyu** [octref/vetur#259]
Code:

    <a v-for="type in verticleTypes" @click="verticleType = type" >{{ type }}</a>

Screenshot:

![](https://i.imgur.com/2Uoauo7.png)

The problem should be fairly obvious.

**Comment by octref** [comment]
`type` is a reserved word for TS. We are using TS grammar for JS and this isn't easily fixable. I recommend avoid naming parameters as `type`.

**Comment by yunyu** [comment]
OK, good to know.
