### ISSUE TITLE
I hope to be able to participate in the project。

### ISSUE THREAD

**Issue by ThinkRealize** [octref/vetur#262]
Hi octref, I like vetur.
I want to be involved, it is more perfect. 
How can I contact you?
What do I need to pay attention to?

**Comment by octref** [comment]
Hey, thanks for your interest in contributing! 👍 

Here is the contributing doc:
https://github.com/octref/vetur/blob/master/.github/CONTRIBUTING.md

Maybe you can first try building the project itself. Then participate in some issues, answer people's questions and find smaller ones to fix (ping me first before sending a PR).

**Comment by octref** [comment]
Closing this issue since there is nothing I need to do, but feel free to ask more questions here and I'll respond.
