### ISSUE TITLE
javascript code does not have code hinting.

### ISSUE THREAD

**Issue by leemove** [octref/vetur#265]
- Platform:Win
- Vetur version: 0.8.3
- VSCode version: 1.13.1
after update to 0.8.3 javascript code does not have code hinting.it's read as htmlcode.

**Comment by octref** [comment]
Please provide screenshot and repro case.

**Comment by thanhps42** [comment]
I same problem too.

![](http://s26.postimg.org/8udbdgljt/screenshot_58.png)

**Comment by octref** [comment]
Do you have vue dependency installed?

What's your `npm list vue` output?

**Comment by leemove** [comment]
![shot](https://user-images.githubusercontent.com/11146494/27475901-5bed7936-5839-11e7-92ae-cd880bc53ce9.png)

**Comment by leemove** [comment]
![shot](https://user-images.githubusercontent.com/11146494/27475901-5bed7936-5839-11e7-92ae-cd880bc53ce9.png)
![ddd](https://user-images.githubusercontent.com/11146494/27476143-2520777c-583a-11e7-83a9-f3e63c2605cb.gif)

**Comment by leemove** [comment]
`npm list vue` out put
```bash
guide@1.0.0 E:\demos\升学指导\guide
`-- vue@2.3.4
```
and my `package.json`
```js
  "dependencies": {
    "axios": "^0.16.2",
    "css-loader": "^0.28.4",
    "lodash": "^4.17.4",
    "vue": "^2.3.3",
    "vue-router": "^2.3.1",
    "vue-style-loader": "^3.0.1"
  },
  "devDependencies": {
    "autoprefixer": "^6.7.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^1.1.3",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "eslint": "^3.19.0",
    "eslint-config-standard": "^6.2.1",
    "eslint-friendly-formatter": "^2.0.7",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-html": "^2.0.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^2.0.1",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.14.1",
    "extract-text-webpack-plugin": "^2.0.0",
    "file-loader": "^0.11.1",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.3",
    "node-sass": "^4.5.3",
    "opn": "^4.0.2",
    "optimize-css-assets-webpack-plugin": "^1.3.0",
    "ora": "^1.2.0",
    "rimraf": "^2.6.0",
    "sass-loader": "^6.0.6",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "url-loader": "^0.5.8",
    "vue-loader": "^12.1.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.3.3",
    "webpack": "^2.6.1",
    "webpack-bundle-analyzer": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.18.0",
    "webpack-merge": "^4.1.0"
  }
```

**Comment by octref** [comment]
Remove vuehelper.

**Comment by leemove** [comment]
it does not work.
i use another computer install vscode and only install vetur.  it also does't have  code hinting.
thank you for you response.

**Comment by octref** [comment]
So downloading this: https://github.com/octref/veturpack
And doing a `npm install`, open it in VSCode installed only with Vetur extension, it doesn't work?

**Comment by ppasieka** [comment]
I have the same problem (Tested with veturpack project) on Windows. It seems that only script section does not work.

No errors in console nor in VLS output.

**Comment by octref** [comment]
This is actually #205 and when we merged vue-language-server this change is lost: https://github.com/octref/vetur/commit/8d08aa31bd1709569f76a864e67f2e502ab3306b

**Comment by octref** [comment]
Fixed and will publish new version soon.

**Comment by octref** [comment]
Upgrade to 0.8.5

**Comment by leemove** [comment]
thank  you very much!

**Comment by octref** [comment]
@ppasieka So 0.8.5 works on stable but not insider for you?

**Comment by ppasieka** [comment]
yes. 
after upgrade to 0.8.5 it worked on stable
in insider release I had to run npm install in extension/client directory. then it worked.
