### ISSUE TITLE
vue-language-server now reports missing v-bind:key directive on v-for

### ISSUE THREAD

**Issue by skycult** [octref/vetur#266]
- Platform: macOS
- Vetur version: 0.8.3
- VSCode version: 1.13.1

## Problem
vue-language-server now reports missing v-bind:key directive on v-for

## Reproducible Case
Use this simple template:

```html
<template v-for="field in schema.fields">
    <component :is="getComponent(field)" :key="field.id"></component>
</template>
```
 The error message is reported on template.
Regards.

**Comment by octref** [comment]
Does not repro for me:

![image](https://user-images.githubusercontent.com/4033249/27480665-30c12908-5819-11e7-8595-2ae3131ab4af.png)

This should be correct per https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/require-v-for-key.md

**Comment by HerringtonDarkholme** [comment]
This is already known. 
Please see https://github.com/vuejs/eslint-plugin-vue/pull/45.

For now you can disable vetur's template lint.

@octref you need place template in an `<template>` to reproduce.

**Comment by samuelsonbrito** [comment]
It is recommended to provide a key with v-for whenever possible, unless the iterated DOM content is simple, or you are intentionally relying on the default behavior for performance gains.

https://vuejs.org/v2/guide/list.html#Mapping-an-Array-to-Elements-with-v-for

Exemple:
`<template>
  <div>
    <h1 v-text="titulo"></h1>
    <ul>
      <li v-for="foto in fotos" :key="foto.id">
        <img :src="foto.url" :alt="foto.titulo">
      </li>
    </ul>
  </div>
</template>`
