### ISSUE TITLE
[vue-language-server] Self-closing should not be used.

### ISSUE THREAD

**Issue by Moerj** [octref/vetur#267]
![qq20170623-191557 2x](https://user-images.githubusercontent.com/13795438/27479912-7881af54-5848-11e7-83e5-b8a7299aeb4c.jpg)

why can not use?

**Comment by octref** [comment]
https://github.com/octref/vetur/pull/235#issuecomment-310531179

**Comment by octref** [comment]
Now at https://octref.github.io/vetur/linting-error.html

**Comment by beeplin** [comment]
I am not sure whether it is a good choice to forbid self-closing tags by default. W3C html5 standard allows self-closing tags when they are `void-elements` or `foreign elements`:

https://www.w3.org/TR/html5/syntax.html#start-tags

![image](https://user-images.githubusercontent.com/13058150/27685341-58ed2e9a-5d00-11e7-9bcc-53172a43195d.png)

Customized vue components, although not covered by html5 standard, might have no reason to disallow self-closing, I think.

**Comment by daekano** [comment]
Agreed with @beeplin -- another example is image and line break tags.

**Comment by octref** [comment]
https://github.com/vuejs/eslint-plugin-vue/issues/48
https://github.com/vuejs/eslint-plugin-vue/pull/54
