### ISSUE TITLE
__vueEditorBridge appears on suggestion list

### ISSUE THREAD

**Issue by ppasieka** [octref/vetur#269]
- Platform: Win
- Vetur version: 0.8.5
- VSCode version: 1.13.1

## Problem
![image](https://user-images.githubusercontent.com/2170707/27483932-aa5508bc-5827-11e7-9e84-49d7fefa0f23.png)

## Reproducible Case

Trigger intellisence (Ctrl + Space) in script tag inside vue file

**Comment by octref** [comment]
I don't have a WIndows machine at hand, but probably some Windows path handling problem.

**Comment by HerringtonDarkholme** [comment]
This is introduced by option contextual typing. We can simply filter it out.
