### ISSUE TITLE
Eslint Error Line 

### ISSUE THREAD

**Issue by emrekaranfil** [octref/vetur#270]
Platform: Win & Mac
Vetur version: 0.8.5

Are this a bug ?  or are i am using wrong,

I get an error like below when .vue format is selected. But code color style very good.

![2017-06-23 16_35_00-](https://user-images.githubusercontent.com/9162729/27484626-9815d1ee-5832-11e7-9a1a-4f3556afe22c.jpg)
![2017-06-23 16_35_50-categories vue - havacidan-com-development-95cc0e97636358ee5c366238802bd899bec30](https://user-images.githubusercontent.com/9162729/27484624-981347d0-5832-11e7-92bc-e80160623f06.jpg)
![2017-06-23 16_35_57-categories vue - havacidan-com-development-95cc0e97636358ee5c366238802bd899bec30](https://user-images.githubusercontent.com/9162729/27484628-981b0d30-5832-11e7-9683-4991738dcf18.jpg)
![2017-06-23 16_37_05-navbar vue - havacidan-com-development-95cc0e97636358ee5c366238802bd899bec30e9d](https://user-images.githubusercontent.com/9162729/27484627-981991b2-5832-11e7-904a-7817cabe2e14.jpg)

Problems are resolved when I select vue-html format. But code color style Incompatible and bad.

![2017-06-23 16_37_38-navbar vue - havacidan-com-development-95cc0e97636358ee5c366238802bd899bec30e9d](https://user-images.githubusercontent.com/9162729/27484625-9814a616-5832-11e7-95de-03ef55297933.jpg)
![2017-06-23 16_42_55-navbar vue - havacidan-com-development-95cc0e97636358ee5c366238802bd899bec30e9d](https://user-images.githubusercontent.com/9162729/27484905-8d8f09c4-5833-11e7-9abb-c8f4b7554a02.jpg)

**Comment by octref** [comment]
Search through existing issues before posting, please?
#266
