### ISSUE TITLE
Error template with external sources

### ISSUE THREAD

**Issue by coderdiaz** [octref/vetur#272]
- Platform: Linux
- Vetur version: 0.8.5
- VSCode version: 1.13.1

I'm working with multiple files by component in vue but now Vetur says `The template root requires exactly one element`, in this implementation I add the template from an html file.

Is it a bug?

![image](https://user-images.githubusercontent.com/1901273/27496601-46838ecc-581c-11e7-8a44-9f6d17ac7772.png)

**Comment by HerringtonDarkholme** [comment]
Please see https://github.com/vuejs/eslint-plugin-vue/pull/44 for more information.

For now you can simply disable the linting.

**Comment by coderdiaz** [comment]
Good, thanks man.

**Comment by HerringtonDarkholme** [comment]
This issue still needs one fix after https://github.com/octref/vetur/pull/294. Please wait...
