### ISSUE TITLE
Using v-for with a <template> results in error "'v-for' directives require 'v-bind:key' directives."

### ISSUE THREAD

**Issue by nelsonlaquet** [octref/vetur#273]
- Platform: Win
- Vetur version: 0.8.5
- VSCode version: 1.13.1

## Problem
When you have v-for as an attribute to \<template>, the linter (presumably?) throws an error stating that you must also have a v-bind:key attribute. When using v-for on \<template> however, it isn't possible to also have a key directive - instead, you add the key to the children elements of the \<template>.

## Reproducible Case
```
<template v-for="i in 10">
	<div v-if="i < 5" :key="i">
		Under 5
	</div>
	<div v-else :key="i">
		5 or over
	</div>
</template>
```
Will result in red squiggles under "\<template>"

**Comment by octref** [comment]
Dup of #261 and #266.
Please search through existing issues next time before posting.

**Comment by rainabba** [comment]
From: https://vuejs.github.io/vetur/linting-error.html

> Set ESLint rules in .eslintrc. An example:

```
{
  "extends": [
    "eslint:recommended",
    "plugin:vue/recommended"
  ],
  "rules": {
    "vue/html-self-closing": "off" // Fix v-for/template/key bug
  }
}
```

**Comment by casp2** [comment]
asa

**Comment by Valar103769** [comment]
> From: https://vuejs.github.io/vetur/linting-error.html
> 
> > Set ESLint rules in .eslintrc. An example:
> 
> ```
> {
>   "extends": [
>     "eslint:recommended",
>     "plugin:vue/recommended"
>   ],
>   "rules": {
>     "vue/html-self-closing": "off" // Fix v-for/template/key bug
>   }
> }
> ```
没有用处
