### ISSUE TITLE
Is there any way to let vetur also work by setting vue->html association?

### ISSUE THREAD

**Issue by liamwang** [octref/vetur#274]
- Platform: Win
- Vetur version: 0.8.5
- VSCode version: 1.13.1

## Problem
With this vscode setting:
```json
  "files.associations": {
    "*.vue": "html"
  },
```
I can do things like:

![2017-06-24_11-58-47](https://user-images.githubusercontent.com/5000396/27505538-b42f1a0a-58d4-11e7-8002-925a416391c5.gif)

This association setting will let vetur not worked. But removing this setting then looses the built in html editing feature.

Is there any way to fix this?

**Comment by octref** [comment]
https://github.com/Microsoft/vscode/issues/29114

Will take some time.
