### ISSUE TITLE
'v-on' directives require that attribute value while use @submit.native.prevent

### ISSUE THREAD

**Issue by xiguaxigua** [octref/vetur#279]
- Platform: macOS
- Vetur version: 0.8.5
- VSCode version: 1.13.1

## Problem
The new version vetur can help us code better with better grammar tips. But sometimes I thank in this scene should not be prompted.
![2017-06-24 10 37 28](https://user-images.githubusercontent.com/9931685/27509368-c414dfa0-592d-11e7-9657-c605ec85f1f3.png)
https://vuejs.org/v2/guide/events.html#Event-Modifiers

**Comment by HerringtonDarkholme** [comment]
Thanks! This is eslint-plugin-vue's issue. We have already logged on upstream's issue board. https://github.com/vuejs/eslint-plugin-vue/issues/49

**Comment by xiguaxigua** [comment]
Thx @HerringtonDarkholme

**Comment by HerringtonDarkholme** [comment]
Fixed in https://github.com/octref/vetur/pull/294
