### ISSUE TITLE
color indicator not working in vue files

### ISSUE THREAD

**Issue by aprilandjan** [octref/vetur#28]
in .scss file:
![image](https://cloud.githubusercontent.com/assets/7011247/22615598/de8665ee-ead2-11e6-9149-8cbf9ea58864.png)

in .vue file:
![image](https://cloud.githubusercontent.com/assets/7011247/22615607/19faf7b6-ead3-11e6-913f-bc141f5ea357.png)

**Comment by octref** [comment]
Actually I don't like it and people are requesting options to disable it even in VSCode...https://github.com/Microsoft/vscode/issues/10943#issuecomment-277258939

I'll add an option if enough people want this.

**Comment by gabrielboliveira** [comment]
As a WA to this, if anyone still wants to have colors on Vue files, install the [Color Highlight](https://github.com/sergiirocks/vscode-ext-color-highlight) plugin and add `"vue"` to the config:

```json
    "color-highlight.languages": [
        "javascript",
        "typescript",
        "scss",
        "css",
        "sass",
        "less",
        "php",
        "xml",
        "html",
        "json",
        "vue"
    ],
```

![Example](https://cloud.githubusercontent.com/assets/11093090/22692094/83790f40-ed24-11e6-8d77-68176aa497f8.png)

**Comment by iatsiuk** [comment]
Please add an option to enable color indicator.

**Comment by aprilandjan** [comment]
@gabrielboliveira Thanks for your advise, the color-highlight plugin works well, and I think the origin color indicator is redundant now...

**Comment by octref** [comment]
I still don't like it. I recommend using @gabrielboliveira's extension instead.
