### ISSUE TITLE
0.8.5 Request textDocument/hover failed.

### ISSUE THREAD

**Issue by cxwwa** [octref/vetur#287]
- Platform: macOS
- Vetur version: 0.8.5
- VSCode version:  1.13.1

## Problem
[Error - 11:27:13 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'target' of undefined
  Code: -32603

**Comment by octref** [comment]
Please provide details for repro the problem. Otherwise there is nothing we can help you with.
