### ISSUE TITLE
Template tag cannot be keyed but vetur shows validation error that v-bind:key is required

### ISSUE THREAD

**Issue by ppasieka** [octref/vetur#288]
- Platform: Win
- Vetur version: 0.8.6
- VSCode version: 1.13.1

## Problem
Template tag cannot be keyed but vetur shows validation error that v-bind:key is required

`'v-for' directives require 'v-bind:key' directives.`

![image](https://user-images.githubusercontent.com/2170707/27531248-335fb810-5a5c-11e7-9cde-ec37c633d0f6.png)

Webpack won't compile when you put `v-bind:key` in template tag

**Comment by octref** [comment]
#273 #266 #261.

**Comment by octref** [comment]
For now you can either disable this rule or disable template lint completely https://octref.github.io/vetur/linting-error.html

**Comment by RokasMuningis** [comment]
@octref - that link is dead, just saying.

**Comment by octref** [comment]
New link is https://vuejs.github.io/vetur/linting-error.html since Vetur was moved to Vuejs organization.

**Comment by rainabba** [comment]
From: https://vuejs.github.io/vetur/linting-error.html

> Set ESLint rules in .eslintrc. An example:

```
{
  "extends": [
    "eslint:recommended",
    "plugin:vue/recommended"
  ],
  "rules": {
    "vue/html-self-closing": "off" // Fix v-for/template/key bug
  }
}
```
