### ISSUE TITLE
'v-for' directives require 'v-bind:key' directives.

### ISSUE THREAD

**Issue by edDimensi** [octref/vetur#289]
Key binding require only on for components, key not need for usual html.
![image](https://user-images.githubusercontent.com/11390039/27534891-26770986-5a71-11e7-9c13-4c08d3a5f030.png)
https://vuejs.org/v2/guide/list.html#Components-and-v-for
How disable notify for html, but enable for componets?

**Comment by octref** [comment]
#288 #273 #266 #261.

Please search through existing issues before making new ones next time. Thank you.
