### ISSUE TITLE
Parser fails for template with inline SVG containing a viewBox attribute

### ISSUE THREAD

**Issue by fiznool** [octref/vetur#291]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://octref.github.io/vetur/

## Info

- Platform: macOS
- Vetur version: 0.8.6
- VSCode version: 1.13.1

## Problem

A template containing an inline SVG without a `viewBox` attribute is parsed just fine:

![working](https://user-images.githubusercontent.com/820863/27542819-5422fa84-5a80-11e7-834b-0b0b17f9bd03.png)

But, the template fails to parse if it contains an inline SVG with a `viewBox` attribute. You get the following error:

```
[vue-language-server] Parsing error: Cannot read property 'startOffset' of undefined'
at: '1,1'
```

![failing](https://user-images.githubusercontent.com/820863/27542829-59cd6b7c-5a80-11e7-9734-94e69cecfae3.png)

**Comment by octref** [comment]
Do you mind pasting the code?

**Comment by fiznool** [comment]
```
<template>
  <div>
    <svg width="24px" height="24px">
      <path class="close-x" d="M 10,10 L 30,30 M 30,10 L 10,30" />
    </svg>
  </div>
</template>
```

**Comment by HerringtonDarkholme** [comment]
Thanks for reporting. This is an upstream bug in eslint-plugin-vue.

**Comment by octref** [comment]
Was just about to say this is an upstream problem, but @HerringtonDarkholme already reported it :-)

**Comment by fiznool** [comment]
Thanks both for the speedy replies 👍

**Comment by HerringtonDarkholme** [comment]
Fixed in https://github.com/octref/vetur/pull/294
