### ISSUE TITLE
 Validation incorrectly indicates that input html tag cannot be self closing

### ISSUE THREAD

**Issue by JamesCrann** [octref/vetur#292]
## Info

- Platform: Windows 8
- Vetur version: 0.8.6
- VSCode version: 1.13.1

## Problem
 Validation incorrectly indicates that input html tag cannot be self closing

![image](https://user-images.githubusercontent.com/2524952/27566865-3c9720d8-5b2b-11e7-9d08-cf2efe407735.png)

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/eslint-plugin-vue/pull/54

**Comment by HerringtonDarkholme** [comment]
Fixed in https://github.com/octref/vetur/pull/294
