### ISSUE TITLE
when i use v-for,an error has occurred

### ISSUE THREAD

**Issue by numens** [octref/vetur#298]
## Info

- Platform: macOS
- Vetur version: 0.8.6
- VSCode version: 1.13.1

## Problem
![image](https://user-images.githubusercontent.com/13229304/27623363-b419238e-5c0e-11e7-9bdc-57e96b4924a7.png)

the problem just like this, it reminds me to use `:key`, but i think that is unnecessary

**Comment by octref** [comment]
Please search through existing closed issues since I've closed like 5 duplicates.
