### ISSUE TITLE
User Snippets not loading correctly

### ISSUE THREAD

**Issue by gabrielboliveira** [octref/vetur#30]
I've created my own snippet for Vue files, but using this plugin it doesn't load any suggestion. For example, adding this snippet configuration:

```json
    "Vue Template": {
        "prefix": "full",
        "body": [
            "<template>\n",
            "</template>\n",
            "<script>",
            "export default {\n\tname: \"$TM_FILENAME\"\n}",
            "</script>\n",
            "<style lang=\"scss\">\n",
            "</style>"
        ],
        "description": "Vue Template"
    }
```

![user snippet](https://cloud.githubusercontent.com/assets/11093090/22649570/acd11cc4-ec62-11e6-81ea-460120ee2eb7.png)

Indeed, it doesn't show any snippet at all. Only when I manually add the `<template>`, `<script>` or `<style>` tags.

**Comment by octref** [comment]
Alright, this will take a larger change on the grammar than I expected. But once it get fixed you should be able to use different snippets in each regions (vue, html, scss, less, js). Might take a few days as I'm busy.

**Comment by octref** [comment]
With the next version you can:
- Use Vue snippet outside `<template>`, `<style>`, and `<script>`
- Use each language's snippet, like scss snippet in `<style lang="scss">`

You won't be able to use html snippet yet, as I'm thinking about introducing vue-html as a new language to give it better syntax highlight / IntelliSense.

**Comment by octref** [comment]
Give it a try in 0.3.3. Let me know any issues!
