### ISSUE TITLE
Nested SCSS elements are unstyled

### ISSUE THREAD

**Issue by wopian** [octref/vetur#31]
Using vetur 0.3.1

Nesting works on everything but a few elements. `div` is expected to be pink - like it's parent, but is displayed with no styling.

![](http://i.imgur.com/GJe6dkf.png)

**Comment by wopian** [comment]
Turns out it's being caused by Color Highlight, where I had a colour reference on the line above before deleting it in example above.

https://gfycat.com/CheeryExhaustedAegeancat

**Comment by wopian** [comment]
It seems to be the first child element doesn't get styled. When it gets pushed down to be the 2nd child it gets the correct styling - and the new first child is unstyled.

https://gfycat.com/PoorWindyDiplodocus

**Comment by octref** [comment]
![image](https://cloud.githubusercontent.com/assets/4033249/22785416/2bbb502c-eea2-11e6-8632-d29565a0ce02.png)


This is default theme on 1.9 stable. Can you turn off other extensions that have anything to do with scss to find which one is causing this?

**Comment by wopian** [comment]
Apologies for delay.

This is with all my current extensions enabled with my theme:
![](http://i.imgur.com/v14O7MA.png)

And this is with all but vetur disabled in the workspace using the default theme:
![](http://i.imgur.com/RvM4lgS.png)

`Notice.vue`
```vue
<template>
  <!-- content -->
</template>

<script>
  // content
</script>

<style lang='scss'>
  @import '~styles/main.scss';

  section[role='alert'] {
    @extend .alert;
    @extend .alert-dismissible;
    border-radius: 0;
    margin-bottom: 0;
    background: darken(white, 2);
    border: 0;
    z-index: 1;

    > div {
      @extend .container;
      display: flex;
      flex-direction: row;
      flex-wrap: nowrap;
      justify-content: space-between;
      align-content: stretch;
      align-items: flex-start;

      div {
        order: 0;
        flex: 1 1 auto;
        align-self: auto;
      }
    }

    P:last-of-type {
      @extend .mb-0;
    }
  }
</style>

**Comment by octref** [comment]
Couldn't believe the original grammar didn't cover single quote for lang attribute...
`<style lang='scss'>` literally wouldn't work.

Just published 0.3.2. Can you try upgrading?

**Comment by wopian** [comment]
Works like a charm on 0.3.2. Never even thought of trying it with double quotes 😆

**Comment by stealthybox** [comment]
@octref
Vetur's super useful! Pushed a couple of my teammates away from WebStorm because of the quality of this plugin.

I've been using vetur with single quotes for a few months now using a different grammar mod.

Basically instead of:
`(?:^\s+)?(<)((?i:template))\b(?=[^>]*lang=["'](jade|pug)(?:\?[^"]*)?["'])`
I do:
`(?:^\s+)?(<)((?i:template))\b(?=[^>]*lang=("(jade|pug)(?:\?[^"]*)?"))|('(jade|pug)(?:\?[^']*)?'))`

This prevents __"jade'__ from being valid.

(Also, the current code is missing a single quote in the negated character class.)
Would you take a quick PR?
Which implementation do you prefer?

**Comment by octref** [comment]
@stealthybox I'm glad you like it, better things are yet to come, like vue API snippet in IntelliSense :D
Definitely let me know what features you & your teammates want. I don't have that much experience writing large Vue apps so I don't know some of the pain points.

Sure, go ahead and send a PR. Thanks for pointing out the bugs.

Just BTW, I'm also in the process of refactoring the grammar, mainly to have a top-level grammar that deals with embedded languages, and one specifically for vue's html. I'll probably push that tomorrow -- let me know if you encounter problems. And you are always welcome to send a PR.

**Comment by octref** [comment]
@stealthybox I'll add CONTRIBUTING.md tomorrow morning to include instructions for running & debugging vetur. Maybe you want to wait until then.

**Comment by wopian** [comment]
Implemented it in [wopian/vue-syntax](https://github.com/wopian/vue-syntax-highlight) for the main sublime theme. 

Haven't had time to hook up the captures to the changed capture groups or test it yet...although when I do, hopefully it'll be seen unlike the issue I created for it over a month ago 😭 

Will cross-post the changes here once I have 😄 

Current:
```js
/(<)(template)\b(?=[^>]*lang=('jade'|"jade"|'pug'|"pug"))/
```

New:
```js
/(<)((?i:template))\b(?=[^>]*lang=(['"])(jade|pug)\3)/
```
![](http://i.imgur.com/QEKn6MT.png)

**Comment by octref** [comment]
Here is what I have and it works fine I think:

https://github.com/octref/vetur/blob/master/syntaxes/vue.YAML#L12
