### ISSUE TITLE
Fix vue's yaml grammar single/double quote

### ISSUE THREAD

**Issue by octref** [octref/vetur#35]
`lang="jade'` is still valid in the current vue.yaml grammar.

@stealthybox if you still want to give it a try.

**Comment by stealthybox** [comment]
Looks like the grammar has just been changed.
This is going to take me some time to test properly.

**Comment by octref** [comment]
The new grammar is not complete yet, but the basic idea is, you have a mega syntax that just checks for these:

```vue
<template></template>
<template lang="pug"></template>
<template lang='pug'></template>
<style></style>
<style lang="scss" scoped></style>
```

you get the point. These grammars are easy to scan through (by your eye or the regex engine), so they are easy to fix and fast to parse.

I think something like `("jade"|'jade'|"pug"|'pug')` would be good enough.

The unfinished part in Vue's SFC spec is tracked here: https://github.com/octref/vetur/issues/36

**Comment by stealthybox** [comment]
Are we planning to support Webpack's Inline Loader Requests?
[Info at the bottom of this doc](https://vue-loader.vuejs.org/en/configurations/pre-processors.html)

The old grammar forked from vue-syntax-highlight seemed to support this.

**Comment by octref** [comment]
Since I have to do a lot of edit to the grammar I fixed it by myself. Next time if you see a problem in the grammar and want to fix it by yourself, go ahead and send a PR! Thanks again.
