### ISSUE TITLE
Follow Vue's SFC spec

### ISSUE THREAD

**Issue by octref** [octref/vetur#36]
The new grammar doesn't handle a few cases for SFC yet.

https://vue-loader.vuejs.org/en/start/spec.html

Especially important are scoped/module style block, src import, postcss, and comment.

**Comment by stealthybox** [comment]
Are we planning to support Webpack's Inline Loader Requests?
[Info at the bottom of this doc](https://vue-loader.vuejs.org/en/configurations/pre-processors.html)

The old grammar forked from *vue-syntax-highlight* seemed to support most of these things.
It searched for a fairly simple condition that allowed for user additions around the `lang` attribute.

**Comment by octref** [comment]
> However, note this makes your Vue component Webpack-specific and not compatible with Browserify and vueify. If you intend to ship your Vue component as a reusable 3rd-party component, avoid using this syntax.

So not yet. We can add that later.
