### ISSUE TITLE
SASS highlighted with CSS grammar

### ISSUE THREAD

**Issue by wopian** [octref/vetur#37]
VSCode: 1.9.1
vetur: 0.3.2

Was just messing around with a test project and discovered that SASS is being highlighted with the CSS grammar instead of SASS - even though the correct grammar is defined

![](http://i.imgur.com/NsyThHi.png)

```vue
<style lang="sass">
  #app
    width: 100vw
    text-align: center
</style>
```

I.e this works when it shouldn't:

![](http://i.imgur.com/PMQeuKt.png)

**Comment by octref** [comment]
Interesting...Working for me for the identical code

Can you try F1 -> Inspect TM Scopes, and show me a screenshot when you put cursor between the sass region? Like so

![image](https://cloud.githubusercontent.com/assets/4033249/22872786/bf5df232-f189-11e6-8bf9-d88d2e9a1751.png)

**Comment by wopian** [comment]
I'm a fool. 

I thought I had `file.associations: { *.vue: vue }` in my user settings. Turns out I had it in the workspace settings in my other projects. 😨
