### ISSUE TITLE
Formatting is ugly

### ISSUE THREAD

**Issue by shijunti19** [octref/vetur#39]
![image](https://cloud.githubusercontent.com/assets/5392211/22916054/d6330488-f2b6-11e6-8187-992bf284da30.png)

**Comment by octref** [comment]
Dup of #38 and #20. Ok guess I'll work on embedded formatter first.

**Comment by octref** [comment]
Are you using https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify by any chance?

**Comment by octref** [comment]
html formatting is working for me, with VSCode's stock html formatter.

![format](https://cloud.githubusercontent.com/assets/4033249/22957664/cf4b9734-f2f7-11e6-8c98-040c4f3909da.gif)

**Comment by shijunti19** [comment]
install vetur
The settings appear
![image](https://cloud.githubusercontent.com/assets/5392211/22957720/2b885b00-f365-11e6-8059-c1d7bc74f57c.png)
`<template>
<div class="weui_panel weui_panel_access">
  <v-loading :complete="complete" :loading="loading" @seeing="getDate">
    <router-link v-for="(item, index) in list" :key="item.id" class="weui_media_box weui_media_appmsg" :to="{ name: '/taobao/view', params: { num_iid:item.num_iid }}">
      <div class="weui_media_hd">
        <img class="weui_media_appmsg_thumb" :src="item.pic_url" alt="">
      </div>
      <div class="weui_media_bd">
        <div class="weui_media_box weui_media_text new_padding">
          <h4 class="weui_media_title " v-html="item.title" style=" margin-bottom:0;"></h4>
          <div class="weui_media_info" style=" margin-top:0;">
            <div class="weui_btn  weui_btn_mini bg-orange weui_btn_inline">￥{{item.discount_price}}</div>
            <div class="weui_btn  weui_btn_mini bg-blue weui_btn_inline" v-if="item.coupon_left_count>0">{{item.coupon_info}}</div>
          </div>
          <div class="weui_media_info" style=" margin-top:0;">
            <span class="weui_media_info_meta f-red" v-if="item.coupon_amount>0">有{{item.coupon_amount}}元优惠券</span>
            <span class="weui_media_info_meta f-green">{{item.nick}}</span>
            <span class="weui_media_info_meta f-blue" title="30日销量">销量：{{item.sell}}</span>
          </div>
        </div>
      </div>
    </router-link>
  </v-loading>
</div>

</template>`

**Comment by octref** [comment]
> <div class="weui_panel weui_panel_access">div class="weui_media_bd"><div class="weui_media_box weui_media_text new_padding"><h4 class="weui_media_title " v-html="item.title" style="margin-bottom:0;"></h4></div></div></div>

You have a div without tag, `div class="weui_media_bd">`.

**Comment by shijunti19** [comment]
@octref 
no
you try style="..."
![image](https://cloud.githubusercontent.com/assets/5392211/22957982/1c40ee9e-f367-11e6-9892-9bfddb440020.png)

**Comment by octref** [comment]
Do you mind pasting the code?

**Comment by shijunti19** [comment]
@octref 

`<template>
    <div class="weui_panel weui_panel_access">
        <div class="weui_media_bd">
            <div class="weui_media_box weui_media_text new_padding">
                <h4 class="weui_media_title " v-html="item.title" style="margin-bottom:0;"></h4>
</div>
</div>
</div>
</template>`

**Comment by octref** [comment]
Thanks, the stock html formats that code fine but vetur doesn't -- I'll look into it.

**Comment by faisalhakim47** [comment]
I think it is related to vscode bug. https://github.com/Microsoft/vscode/issues/17849
Has been fixed since 1.9

**Comment by octref** [comment]
Thanks, that should be it. I'll port it over to the language server.
