### ISSUE TITLE
make emmet only invoke in style tag

### ISSUE THREAD

**Issue by g0ld3lux** [octref/vetur#40]
is there a way , i can use emmet css and emmet html
hand in hand in vue files

if i enable it...
if i try to use emmet for html
i cant get it to work

```
"emmet.syntaxProfiles": {
        "blade": "html",
        // Activate this if you will Heavily Style
        "vue": "css"
    },
```

doing something like this
pb! 
```
padding-bottom:  !important;
```
when i do div.row
```
display: .row;
```

so is there a way i can use both emmet css and html
without having conflict?

lets say make the scope only apply to style tag for css
and template tag for html?

**Comment by octref** [comment]
Can you be a bit more specific. Which part doesn't work?

```
<template>
div.row // this emmet expansion works for me
</template>

<style>
div {
  pb! // this emmet expansion also works for me
}
</style
```

**Comment by octref** [comment]
Umm, sorry for the bad configuration I suggested before in the README.

With 0.3.3, now you can drop 
```json
"emmet.syntaxProfiles": {
  "vue": "css"
}
```

and emmet will work as intended in each regions.

**Comment by octref** [comment]
Oops, ignored what I said before. Can you upgrade to 0.3.5, and have this:

```json
"emmet.syntaxProfiles": {
  "vue-html": "html"
}
```

and let me know if it works for you.

![vetur](https://cloud.githubusercontent.com/assets/4033249/23128124/bbe685a2-f74b-11e6-9649-b8c8c76787a2.gif)
