### ISSUE TITLE
Remove sass grammar

### ISSUE THREAD

**Issue by octref** [octref/vetur#41]
This should be provided by another extension.

**Comment by octref** [comment]
Won't bother for now...

**Comment by wopian** [comment]
👍 Current syntax highlighting provided by vetur is considerably poor compared to the main Sass syntax extension: https://github.com/robinbentley/vscode-sass-indented. Also has snippets 🎉 

Vetur:
![](http://i.imgur.com/oqIsmac.png)
![](http://i.imgur.com/msIdkQR.png)

Sass
![](http://i.imgur.com/WKc3gcp.png)
![](http://i.imgur.com/EqE9Njv.png)

**Comment by octref** [comment]
sass-indented has updated grammar from https://github.com/P233/Syntax-highlighting-for-Sass. I'll remove the current sass definition then.

**Comment by octref** [comment]
Decided to bundle https://github.com/robinbentley/vscode-sass-indented grammar directly.
