### ISSUE TITLE
*.vue files Emmet  isnt work!

### ISSUE THREAD

**Issue by duleigiser** [octref/vetur#44]
In template tag, Emmet syntax is not available.sucks！

**Comment by cupools** [comment]
Add the following to your setting and it works for template, but not stylesheet.
```js
"emmet.syntaxProfiles": {
  "vue": "html"
},
```

**Comment by Huanguolin** [comment]
Me too when i update to 0.3.3. So i rollback to  0.3.2.

**Comment by octref** [comment]
This is fixed in 0.3.5. Try update.

Basically, region between `<template>` is now marked as **vue-html** instead of **html** to provide better support for vue's interpolation and directives.

You need to add this to your setting:

"emmet.syntaxProfiles": {
  "vue-html": "html"
}

![vetur](https://cloud.githubusercontent.com/assets/4033249/23128064/6a59a444-f74b-11e6-93b2-c5f3f9f926c4.gif)

**Comment by duleigiser** [comment]
it works！thanks~

**Comment by muratbsts** [comment]
It works for emmet but does not working vue snippets at this time. Is there any solution for use vue snippets + emmet features both?

![image](https://user-images.githubusercontent.com/1137480/27425653-cd7aa662-5741-11e7-973d-31188ac0bb56.png)

**Comment by octref** [comment]
If you are using   `"emmet.useNewEmmet"`, it's not supported in vetur yet but probably will be next month.

**Comment by octref** [comment]
You can subscribe to https://github.com/Microsoft/vscode/issues/29114

**Comment by muratbsts** [comment]
I don't know what features are included new emmet. But I did set `"emmet.useNewEmmet"` as false and it works now. Thank you @octref God bless you. :smile:

**Comment by HintikkaKimmo** [comment]
I got emmet to work in Vue files by doing following. Please not that emmet.syntaxProfiles (commented out) seem to break emmet in standard HTML for me and I cannot understand why. 

```

  "emmet.useNewEmmet": true,
  // "emmet.syntaxProfiles": {"vue-html": "html"},
  "emmet.includeLanguages": {"vue-html": "html"}
```
