### ISSUE TITLE
Not highlighting vue-html.

### ISSUE THREAD

**Issue by hworld** [octref/vetur#45]
I have .html files set up to use the vue-html language by default. I have my templates in separate .html files. Up until the latest version it worked great. For some reason with latest version (0.3.5) it's not showing any highlighting anymore. I don't have any template tags or anything around the content since it's just straight up .html files.

**Comment by octref** [comment]
Can you post a screenshot?

**Comment by octref** [comment]
I was able to repro it. It's fixed, but I want to wait a bit to see if there is other problems with the new grammar, fix them all together and publish a new version.

**Comment by hworld** [comment]
Sounds good! Thanks for the quick look into it.

**Comment by hworld** [comment]
By the way, I patched my current install with the fix and it seems to have worked. The only current thing I can see is that I no longer get autocompletions of tags.

If I type in `<ul></` it won't show the auto-close for the ul anymore.

**Comment by octref** [comment]
> I patched my current install with the fix and it seems to have worked.

Great!

> If I type in <ul></ it won't show the auto-close for the ul anymore.

Would you mind opening a new issue? I want to keep that tracked. Seems vue-html is not using html's language service.
