### ISSUE TITLE
HTML language service no longer working

### ISSUE THREAD

**Issue by hworld** [octref/vetur#46]
I no longer get autocompletions of tags in vue-html language mode. 
Easy test case: type in `<ul></` it won't show the auto-close for the ul anymore.
Emmet seems to no longer work either. Typing `div.test` and pressing tab just inserts a tab.

**Comment by octref** [comment]
For emmet:

![image](https://cloud.githubusercontent.com/assets/4033249/23146980/8a48f300-f7a9-11e6-85f3-f4b840511835.png)

**Comment by hworld** [comment]
Ah! Sorry about the emmet one. I didn't see that.

**Comment by octref** [comment]
Published 0.4 which resolves this problem. Give it a try.

**Comment by Astray-git** [comment]
Please mention emmet setup in changelog..

**Comment by octref** [comment]
@Astray-git Isn't that in the README?

**Comment by hworld** [comment]
Still not working for me, actually. I have a `.html` file of vue template code and the file association is set to `vue-html` and all that works. Syntax highlighting is correct. It's still not treating it like HTML and giving me tag completions, though. I think this new issue is saying the same thing: https://github.com/octref/vetur/issues/80

**Comment by octref** [comment]
When talking about vue-html, I was referring to the html part in vue file. I opened #81 for your request.
