### ISSUE TITLE
template tag issue

### ISSUE THREAD

**Issue by broven** [octref/vetur#48]
![screen shot 2017-02-21 at 11 23 21 am](https://cloud.githubusercontent.com/assets/12854613/23149622/41b9f8d0-f828-11e6-8ae1-0dcc07a953bb.png)
not highlight after meet template tag which are not the right template tag.

**Comment by octref** [comment]
Using `<template>` inside `<template>`...is that even allowed for vue SFC?

**Comment by octref** [comment]
NVM it's a bug.

**Comment by octref** [comment]
Will be in next release: 

![image](https://cloud.githubusercontent.com/assets/4033249/23171343/3a274080-f820-11e6-9a89-b6e93e2c1573.png)

**Comment by octref** [comment]
0.3.6 released. Upgrade and give it a try.

**Comment by CalebKester** [comment]
@octref I'll move my feedback over to this ticket. I tried it and it works... except if there's anything inside of template. If you send me the code I can just test it out if you don't want to make a release.
![image](https://cloud.githubusercontent.com/assets/1319995/23183559/1b0a4e28-f842-11e6-9c6c-58826446c5b4.png)

**Comment by octref** [comment]
Thanks -- I ignored that. It's tracked in #52 and I'll get to it when I have time.
