### ISSUE TITLE
how to support cssnext syntax

### ISSUE THREAD

**Issue by 445141126** [octref/vetur#50]
I want syntax hightlight without no lang set. I just use cssnext for nest selectors.

lang="less" 
![image](https://cloud.githubusercontent.com/assets/1384521/23162401/cfee5a0c-f868-11e6-8382-8cc6c6460815.png)

hightlight ok.

no lang set

![image](https://cloud.githubusercontent.com/assets/1384521/23162419/e5348aee-f868-11e6-8935-3def3c861247.png)

 error hightlight

**Comment by 445141126** [comment]
or i just want less syntax hightlight default

**Comment by octref** [comment]
When not specifying lang, `<style>` defaults to css, according to [Vue SFC spec](https://vue-loader.vuejs.org/en/start/spec.html).

![image](https://cloud.githubusercontent.com/assets/4033249/23167879/23cbe0ae-f814-11e6-89d8-c6841c38d173.png)

vetur only builds support according to Vue SFC. Sorry.

**Comment by octref** [comment]
Oops, I ignored cssnext part. If there is a good postcss/cssnext grammar out there, I can support it. But I wouldn't want to write postcss support from scratch.

**Comment by 445141126** [comment]
#https://github.com/postcss/postcss/issues/409#issuecomment-156291882
There are sublime and atom postcss syntax hightlight

**Comment by octref** [comment]
OK. This looks more promising though: https://github.com/y0ssar1an/CSS3

I'll look into it and have it by next version.

**Comment by octref** [comment]
CSS3 uses Sublime Text specific grammar, so I guess the best I can do is to port the Atom PostCSS extension, or include the grammar from https://github.com/azat-io/atom-language-postcss

**Comment by octref** [comment]
![image](https://cloud.githubusercontent.com/assets/4033249/23229172/3fc055ca-f90d-11e6-8d33-a46f0342cc5a.png)

Will be available in next release.

**Comment by ElvisKang** [comment]
It seems that vetur doesn't support the feature 'nesting' of cssnext

**Comment by devhbh** [comment]
I also found vetur doesn't support nesting syntax.

**Comment by octref** [comment]
For PostCSS, you only have syntax highlight.
Vetur was using CSS error checking for PostCSS, and I just disabled that.
