### ISSUE TITLE
Use of <template> breaks syntax highlighter

### ISSUE THREAD

**Issue by CalebKester** [octref/vetur#51]
I've noticed that the syntax highlighter doesn't support cascading `<template>` tags. If I try to do this inside of a component the highlighting breaks.

http://vuejs.org/v2/guide/list.html#Template-v-for

![image](https://cloud.githubusercontent.com/assets/1319995/23176087/3dbe2324-f827-11e6-8fbe-8cddf41dd423.png)

**Comment by octref** [comment]
Dup of #48. I wanted to wait a bit for another fix, but I guess I'll do a minor release...

**Comment by CalebKester** [comment]
Sorry, I did a terrible job of searching issues.

**Comment by octref** [comment]
No worries. Just released 0.3.6. Upgrade and give it a try.
