### ISSUE TITLE
Handle tag-stuff for template in vue-html

### ISSUE THREAD

**Issue by octref** [octref/vetur#52]

**Comment by broven** [comment]
another bug about template tag.


```
<template >        //extra space
  <div>
  </div>
</template>
------------------------
<template lang="html">
  <div>
  </div>
</template>
------------------------
these will break highlight

but `<template lang="pug">` is ok..



```

**Comment by octref** [comment]
Both cases aren't in Vue's SFC spec so I don't want to support them.
Likewise, `<TEMPLATE>`, `<template lang="PUG">` etc won't be supported.

**Comment by octref** [comment]
Alright although I don't intend to support `<template >` or `<template lang="html">`, they won't break syntax highlighting in the next version.

**Comment by iamiota** [comment]
I use [element](http://element.eleme.io/) get same bug:
````html
    <template>
        <el-table>
            <el-table-column>
                <template>
                    <p></p>
                </template>
            <!-- no highlight start -->
            <el-table-column>
       <el-table>
    </template>
<!-- no highlight end -->
````
![WX20170223-151001.png](https://ooo.0o0.ooo/2017/02/23/58ae8af499083.png)

**Comment by octref** [comment]
Try upgrading to 0.3.7.

**Comment by lbineau** [comment]
Fixed the issue! Thanks for fixing this so fast.
