### ISSUE TITLE
Problem with emmet and the template tag in VSCode 1.9.1

### ISSUE THREAD

**Issue by mogita** [octref/vetur#53]
**OS**: OS X 10.11.6
**VSCode**: 1.9.1
**vetur**: 0.3.6

**Installed Extensions:**

- Code Runner
- One Monokai Theme
- vetur
- vscode-icons

**Procedures to re-produce the issue:**

1. Disable all other extensions
1. Insert `files.associations` and `emmet.syntaxProfiles` settings provided in vetur's README
1. Create a `test.vue` file
1. Go to `test.vue`'s tab, type `template` and hit the Tab key, some spaces are inserted, while it should generate the `template` tags. `div.class-name`, `script` or `style` won't work either. Screenshot (~2MB):
![image](http://ogh7h5pok.bkt.clouddn.com/1135748385406977)
1. Comment out `files.associations` in the settings
1. Go back to `test.vue`'s tab, type `template` or `div` and Tab, they work as expected. And codehighlight too. Screenshot (~4MB):
![image](http://ogh7h5pok.bkt.clouddn.com/1135754274209794)
1. After this, comment out `emmet.syntaxProfiles` in the settings, Tab key still works. Even after vetur was uninstalled, VSCode seems to handle the emmet just fine. As long as I don't have the `files.associations` setting, emmet never breaks.

Meanwhile things like `sass` support worked as expected, as VSCode complained about the grammar if vetur was disabled or `files.associations` setting was commented out.

**Comment by octref** [comment]
Thank you so much for your detailed description. Can you enable vetur and have this in your VSCode setting to see if it works for you?

```json
  "emmet.syntaxProfiles": {
    "vue-html": "html",
    "vue": "html"
  }
```

The problem is, this is how vetur marks each region:

```vue
<template>    // vue
  <div></div> // vue-html
</template>   // vue
              // vue (1)
<style>       // vue
              // css
</style>      // vue
```

By adding `vue-html: html`, you are saying "use html emmet in vue-html" region.  
Similarly, to use emmet in vue region, you need `vue: html` in emmet syntax profile.

Thanks again. I'll add it to README.
