### ISSUE TITLE
The code hint is not valid in vue-html

### ISSUE THREAD

**Issue by OYsun** [octref/vetur#54]
Hi,I'm working on VueHelper,Thanks for the issuse( https://github.com/OYsun/vscode-VueHelper/issues/16 ) you raised, I have fixed the problem, but there is a little bit of error.In my own VueHelper project package. json configuration is as follows：
  ```
 "extensionDependencies": [
        "octref.vetur"
    ],
"contributes": {
        "snippets": [
            {
                "language": "vue-html",
                "path": "./src/snippets/html.json"
            },
            {
                "language": "html",
                "path": "./src/snippets/html.json"
            }
        ]
    }
 ```
So install vuehelper will automatically install vetur，But in the template of vue code hints don't work，In html region, html snippet is not available:

```
<template>          // vue
    <div></div> // html/vue-html (isn't works )
</template>         // vue

```
VueHelper in HTML code snippet of this part in vue file doesn't work, but in the HTML file can be work
![bug01](https://cloud.githubusercontent.com/assets/21058462/23200857/af4fdbe6-f911-11e6-89df-ae2239cfed56.png)
![bug02](https://cloud.githubusercontent.com/assets/21058462/23200888/d9eb06a0-f911-11e6-80ae-6d4e7931a5ea.png)

Any guidance would be greatly appreciated！

**Comment by octref** [comment]
In html your js snippet wouldn't work either, however if you try to define the snippets in F1 -> Preference: Open User Snippets -> JavaScript then snippet will be shown for embedded language.

This is a bug of VSCode and I opened an issue for it: https://github.com/Microsoft/vscode/issues/21046

**Comment by octref** [comment]
It's working for html, as html is the top-level language in a html. The javascript snippets isn't working in html's `<script>`, either. I'll work on a PR to VSCode.

**Comment by octref** [comment]
@OYsun https://github.com/Microsoft/vscode/issues/21046 has been resolved, so you can get snippets for each languages in VSCode Insiders. If not using Insiders, this will be available in VSCode's next monthly release.

![is](https://cloud.githubusercontent.com/assets/4033249/23932850/ce18733a-0910-11e7-954e-86e9c2ad7ad0.gif)

**Comment by octref** [comment]
This is already in March release.
