### ISSUE TITLE
How Stylus in ".vue" file activate intelliSense

### ISSUE THREAD

**Issue by mqhe2007** [octref/vetur#55]
![qq 20170222154657](https://cloud.githubusercontent.com/assets/13450661/23202383/acb9d8bc-f918-11e6-9478-c5a6aaa76937.png)

example:
input "di"
expect "display"

**Comment by octref** [comment]
I'll turn it off for stylus region then. Seems https://github.com/d4rkr00t/language-stylus does have IntelliSense. I'll look into how to integrate that.

**Comment by kyjo2014** [comment]
I have installed lang-stylus plugin. however the intellisense still not work in the ".vue" file. What else should   i do

**Comment by octref** [comment]
That plugin only works for stylus files. I need to integrate its language server into vetur's language server to make the IntelliSense work. That'll take some time.

**Comment by HerringtonDarkholme** [comment]
Stylus Intellisense has been merged into master branch.

Note stylus support is, sadly, very basic. The main hurdle is Stylus compiler itself, which is full of inconsistency and inadequacy. 

I currently don't want to investigate more effort on Stylus. But contribution from Stylus users are always welcome.
