### ISSUE TITLE
Passing eval props in the template breaks syntax highlighting

### ISSUE THREAD

**Issue by utkukaratas** [octref/vetur#58]
...
        <product-list-view  :foo=bar  :pagination=false>
        </product-list-view>

        </template>

        <script>
            ... parses as if html :/ ...
        </script>

Because of ":foo=false" property passing rest of the document will be considered as html. I could swear it was working before the latest update.

Version is the latest (0.3.6)

**Comment by octref** [comment]
`<product-list-view  :foo=bar  :pagination=false>` is not valid vue syntax, afaik.

Isn't it like `<tag :foo="bar" :pagination="false">`?

Or can you kindly point me to the vue documentation / code example that uses this syntax?

**Comment by utkukaratas** [comment]
Whoa! You're right. It does work without the quotes but I can't find anything mentioning the behavior in the docs. Thanks for the heads up. Closing...
