### ISSUE TITLE
ESLint is not working

### ISSUE THREAD

**Issue by ppasieka** [octref/vetur#59]
Vetur 0.3.6
VS Code 1.9.1

After update to this version my vue files are not scanned by eslint, but when I change language mode to HTML then all syntax errors are shown.

My settings:
  ```
"files.associations": {
    "*.vue": "vue"
  },
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "html",
    "vue"
  ],
  "emmet.syntaxProfiles": {
    "vue-html": "html",
    "vue": "html"
  }
```

**Comment by octref** [comment]
Can you post a screenshot?

Also, did you install other vue extensions?

**Comment by soakit** [comment]
update to Vetur 0.3.8

**Comment by ppasieka** [comment]
I tried different vue extensions but always one at the time ( first completely I was removing extension before trying another). Before Vetur I worked with weex extension for few months. 

I'm sure that ESlint worked with vetur on my machine for some time, but I am not sure which version it was exactly. For last two weeks I was working with C# code and during this period I was updating Vetur but never work with it. Yesterday I noticed that ESLint is not working anymore.

Here is screenshot when Vue is selected:

![vue](https://cloud.githubusercontent.com/assets/2170707/23292885/0843d9c6-fa63-11e6-9243-be37d4a84998.png)

And here when I change language to HTML

![html](https://cloud.githubusercontent.com/assets/2170707/23292904/2412dc7e-fa63-11e6-8bad-ca2a0fbf58a3.png)

PS> I updated vetur to 0.3.8 and problem remains
Here is more detailed extension list

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.6|
|githistory|donjayamanne|0.1.5|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|Ionide-FAKE|Ionide|1.2.3|
|Ionide-fsharp|Ionide|2.23.1|
|Ionide-Paket|Ionide|1.6.1|
|csharpextensions|jchannon|1.2.0|
|language-haskell|justusadam|2.0.0|
|csharp|ms-vscode|1.7.0|
|debugger-for-chrome|msjsdiag|2.5.3|
|vetur|octref|0.3.8|
|ejs-language-support|QassimFarid|0.0.1|
|sass-indented|robinbentley|1.3.0|
|elm|sbrink|0.8.3|
|vim|vscodevim|0.5.3|
|bootstrap-3-snippets|wcwhitehead|0.0.9|

PS2> for few minutes I switch to weex and ESLint worked with vue files

**Comment by ppasieka** [comment]
Ok. Problem solved :) My mistake ;)

I usually work with this application by opening solution root (with multiple smaller projects inside). But this time I opened ONLY web application folder (as root) and I had there some old workspace setting file with eslint settings 

```
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "html",
    "weex"
  ],
```

Sorry for wasting your time

**Comment by octref** [comment]
No worries -- you are not the first one making this mistake.

I'll add that to ISSUE_TEMPLATE as a hint.
