### ISSUE TITLE
Tags after template haven't hight light

### ISSUE THREAD

**Issue by Li-Alex** [octref/vetur#60]
Vetur 0.3.6
VS code 1.9.1

when I add "*.vue": "vue" into files.associations, 
the tags after template that uses "v-if" haven't hight light.
when I remove "v-if",  it hight light correctly.
maybe the upgrade of vscode cause this problem

![image](https://cloud.githubusercontent.com/assets/16162468/23252858/4403bc40-f9ed-11e6-8156-f351d0647d37.png)

**Comment by octref** [comment]
Dup of #48 and #52. Try upgrading to 0.3.8.
