### ISSUE TITLE
Template lang attribute with html support

### ISSUE THREAD

**Issue by lbineau** [octref/vetur#61]
## Expected
If template do not have any lang attribute the syntax works and should work with ```lang="html"```
```vue
<template>
  <section class="confirm-address">
    <div class="section-waiting__title">
    </div>
  </section>
</template>
```
```vue
<template lang="html">
  <section class="confirm-address">
    <div class="section-waiting__title">
    </div>
  </section>
</template>
```
## Problem
If I add ```lang="html"``` the color syntax do not works anymore.
http://take.ms/SOaUp

**Comment by broven** [comment]
#52

**Comment by octref** [comment]
Try upgrading to 0.3.7. @broven Thanks for marking it as dup.
