### ISSUE TITLE
File Icon Theme Support

### ISSUE THREAD

**Issue by crimx** [octref/vetur#63]
Can you make it support the file icon theme?

Before Installation
![1](https://cloud.githubusercontent.com/assets/6882794/23266067/9f3b58dc-fa21-11e6-85e6-1a0fb2f916d2.png)

After Installation
![2](https://cloud.githubusercontent.com/assets/6882794/23266083/a991140c-fa21-11e6-9393-5c1337404fd9.png)

**Comment by octref** [comment]
I don't know what you are using, but this is with vscode-icons:

![image](https://cloud.githubusercontent.com/assets/4033249/23268023/795ba2b4-f9ba-11e6-9917-d1f187e2bf90.png)

**Comment by octref** [comment]
This should be reported to the theme extension you are uisng. Thanks.

**Comment by crimx** [comment]
I was using the default icon theme.  `vscode-icons` is great, thanks.
