### ISSUE TITLE
Incorrect highlighting for "in" operator

### ISSUE THREAD

**Issue by fenivana** [octref/vetur#65]
![screen shot 2017-02-24 at 10 41 17 am](https://cloud.githubusercontent.com/assets/11750532/23288327/e4092d48-fa7d-11e6-8655-64e94c7a1b1d.png)

Version: 0.3.8

**Comment by octref** [comment]
The problem is you are using `type`, which is a reserved word in TS, and VSCode is using TS grammar for JS...

I'll look into going back to Atom's JS grammar, but it doesn't have syntax highlighting as good as VSCode's TS grammar...

**Comment by fenivana** [comment]
Okay, I'd change the variable name. Thanks!

**Comment by octref** [comment]
I'll try to get this fixed. It doesn't sound right to force you to not use a variable name, because the grammar is wrong.

**Comment by octref** [comment]
The Atom grammar doesn't really play well with VSCode's theme. There is literally no highlighting...

![image](https://cloud.githubusercontent.com/assets/4033249/23351109/25e4c8ba-fc8d-11e6-8838-d903da9ee30f.png)

A proper fix would include either 
- Reduce VSCode's TS language grammar to only have JS features
- Properly port Atom's JS grammar to VSCode so it has right syntax-highlighting.

But both would require a lot of time which I don't have right now.

**Comment by octref** [comment]
I think the easiest way is to just avoid using `type` as a variable.
