### ISSUE TITLE
No autocompletion of standard methods?

### ISSUE THREAD

**Issue by TheDutchCoder** [octref/vetur#69]
Sorry for opening an issue for this, as it's more of a question, but it seems like this extension doesn't provide any Vue built-in method references like `mounted()` or `ready()`.

Am I missing something?

![image](https://cloud.githubusercontent.com/assets/1668207/23446407/f31b4500-fe10-11e6-82fd-fd2863d845b2.png)

**Comment by octref** [comment]
Subscribe to https://github.com/octref/vetur/issues/26.
I'm working on it https://github.com/octref/vls.

**Comment by TheDutchCoder** [comment]
Ah thanks!
