### ISSUE TITLE
SCSS Variables & Mixin Highlighting

### ISSUE THREAD

**Issue by rmtuckerphx** [octref/vetur#7]
The highlighting doesn't work for SCSS for the following sample:

```
<style lang="scss">
  @import "scss/bootstrap/mixins/_buttons.scss";
  $brand-primary: #3c763d !default;
  $btn-primary-color: #fff !default;
  $btn-primary-bg: $brand-primary !default;
  $btn-primary-border: darken($btn-primary-bg, 5%) !default;
  .btn-primary {
    @include button-variant($btn-primary-color, $btn-primary-bg, $btn-primary-border);
  }
</style>
```

All shows formatted when in a .scss file

**Comment by octref** [comment]
Can you post a screenshot? Works for me:

![image](https://cloud.githubusercontent.com/assets/4033249/20359123/4df16ee4-abe3-11e6-84f3-9064548b7553.png)

**Comment by octref** [comment]
Will reopen if you can provide more info.

**Comment by rmtuckerphx** [comment]
This is what mine screen looks like.

![scss-style](https://cloud.githubusercontent.com/assets/247472/20544611/282af894-b0c8-11e6-967b-3516c61f7138.JPG)

**Comment by octref** [comment]
Do you have

```json
"files.associations": {
  "*.vue": "vue"
}
```

in your user setting?

**Comment by octref** [comment]
NVM, this extension only works for vue file. scss file error should be reported to https://github.com/Microsoft/vscode. Meanwhile you can turn off scss validation by:

```
  "scss.validate": false
```
