### ISSUE TITLE
Syntax highlighting doesn't work with "text/babel" script tags

### ISSUE THREAD

**Issue by willworks** [octref/vetur#70]
### Version
 - vscode: 1.9.1
 - vetur: 0.4.0
 - os: macOS Sierra 10.12.3

### Steps to Reproduce:
 - create a <script type="text/babel"> tag in a .vue file.
 - syntax highlighting doesn't work inside the tag. If it is changed to text/javascript then syntax highlighting works.
 - but syntax highlighting work in webstorm in this situation.

**Comment by octref** [comment]
Can you post a screenshot?

Also, for Vue SFC there is no need to specify `type="text/babel"`.

**Comment by willworks** [comment]
![screen shot 2017-03-02 at 10 33 07](https://cloud.githubusercontent.com/assets/5542777/23490482/c7185258-ff33-11e6-9e36-c7b78067c11d.png)

That is because es6 was not support well before in webstorm or other editors, so they add `type="text/babel"` to improve es6 highlight support. But when I use vscode I found syntax highlighting doesn't work inside the tag with your plugin

**Comment by octref** [comment]
OK, I'll fix it for next release.
