### ISSUE TITLE
wordbase suggestion no work

### ISSUE THREAD

**Issue by soundtina** [octref/vetur#73]
![image](https://cloud.githubusercontent.com/assets/4946901/23536586/dd66910a-0000-11e7-8aa9-9be21d297e0e.png)
(when i didn't use vetur the **wordbase** suggestion works fine)
but
when i use vetur it just broken 
![Uploading image.png…](https://cloud.githubusercontent.com/assets/4946901/23536542/98318892-0000-11e7-8d59-0c99a400b426.png)

**Comment by octref** [comment]
Will be fixed correctly by #26, but it'll take some time.
I'll look into temporarily using word based suggestion...

**Comment by octref** [comment]
We already have word-based IS in master. Will be available next release.
