### ISSUE TITLE
how to enable eslint autofix for vue file with this extension

### ISSUE THREAD

**Issue by Hanruis** [octref/vetur#74]
sorry for create a new issue ...i canot find your email..

is there any way to enable autofix with this extension ? 
i search all issues and doc , can not find some words relate .... 

env:
vscode , no other vue extension.

 vscode settings.
```
    "eslint.autoFixOnSave": true,
    "eslint.enable": true,
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        "vue",
        "html"
    ],
```

eslint extension version v1.2.7
eslint version v3.12.2

**Comment by octref** [comment]
No autofix is available now, unfortunately.
