### ISSUE TITLE
Better intellisense for `this` references in script block

### ISSUE THREAD

**Issue by sandersn** [octref/vetur#75]
I'm working on a [plugin for the typescript language service](https://github.com/sandersn/vue-ts-plugin) that will provide better intellisense for `this` references in an options object inside the script block of a vue file. In a .js (or .ts) file, the call to `new Vue(...)` can provide a contextual type to the object literal.

```ts
import Vue from 'vue'
const app = new Vue({
  data: { greeting: 'hi' },
  methods: {
    m1() {
      // Typescript language service can now offer 'greeting' as a completion
      // and also knows that greeting: string.
      // (in both .js and .ts files)
      this./**/greeting
    }
  }
});
```

But inside a Vue file, the typical code is just `export default { ... }`, so there is no such clue to the language service that the default-exported object literal is special.

```vue
<script>
export default {
  data: { greeting: 'hi' },
  methods: {
    m1() {
      // no completions here, and greeting: any
      this./**/greeting
    }
  }
}
```

To fix this, the plugin generates a synthetic `new Vue(...)` call to wrap the object literal, plus a synthetic `import Vue from "vue"` statement.

Right now the installation process is complicated, but I hope that it will be as easy as making sure that vetur is installed, then:

```sh
$ npm install vue-ts-plugin
```

Add a tsconfig.json with a plugins entry:

```json
{
    "compilerOptions": {
        "plugins": [{ "name": "sample-ts-plugin" }]
    },
    "files": [
        "test.vue",
        "other.vue",
    ]
}
```

However, it does not currently work so I'm investigating to see what changes are needed. The plugin loads and starts logging but the types and completions are still the old ones. I'll create PRs if there are changes needed in vetur.

A few notes:

1. The plugin depends on unfinished code in Typescript that may be release by 2.3.
2. vue's d.ts file will need to be updated after Typescript 2.3's release to use the new `ThisType` feature.
3. @octref mentions that vuex also doesn't work well right now. I need to learn more about vuex, but it looks like the `ThisType` feature would also address the basic vuex transformation.

**Comment by octref** [comment]
Here is the main entry for `onCompletion` and `onCompletionResolve`: https://github.com/octref/vetur/blob/master/server/src/htmlServerMain.ts#L168-L187

The language host is created here:
https://github.com/octref/vetur/blob/master/server/src/modes/javascriptMode.ts#L27-L53
If you override the `doComplete` in `javascriptMode` it should provide your new completion items when typing between `<script>`.

I think you would find this helpful -- with this you can set breakpoints in `/server/src` and debug it.
https://github.com/octref/vetur/blob/master/CONTRIBUTING.md

Will have more time later tonight to look into this.
