### ISSUE TITLE
format bugs: html attr wrap 

### ISSUE THREAD

**Issue by beeplin** [octref/vetur#77]
When vscode settings has `"html.format.wrapAttributes": "force",` (or `force-align`)， formatting of vue file looks like this:

![image](https://cloud.githubusercontent.com/assets/13058150/23576606/27496cc2-00e5-11e7-9253-c8644058f04f.png)
the indentation is all broken.

I am not sure if this is veture's bug or vscode's.

vscode: 1.10.1
veture: 0.4.1
os: windows 10 x64

**Comment by beeplin** [comment]
it turns out that this is due to vetur.

HTML file works OKAY with `"html.format.wrapAttributes": "force-aligned"`:
![image](https://cloud.githubusercontent.com/assets/13058150/23576793/2442d982-00ea-11e7-9a57-ed9e7c7b513e.png)

But same code has broken indentations for VUE files:
![image](https://cloud.githubusercontent.com/assets/13058150/23576799/55c7a9ec-00ea-11e7-9936-66f17b66416a.png)

**Comment by octref** [comment]
Is it that html will also be broken without `"html.format.wrapAttributes": "force-aligned"`?

vetur like html is using jsbeautify, but I don't want to add too many options. I'm thinking just use `force-aligned` as default -- will that be OK?

**Comment by beeplin** [comment]
the vue template only breaks with `force-aligned` and `force`.  `auto` and `force-expand-multiline` is fine.

As for the second question: I suggest just following vscode's setting of `html.format.wrapAttributes`:
![image](https://cloud.githubusercontent.com/assets/13058150/23583546/9660cb12-0182-11e7-98aa-77c3d409f02b.png)

I am not sure why it behaves differently in HTML and Vue files. I suppose vetur is calling the same API as vscode does when doing reformat. Is vscode using jsbeautify too?

**Comment by octref** [comment]
Closing in favor of #82.

**Comment by EliazTray** [comment]
what is your color theme?  @beeplin

**Comment by beeplin** [comment]
one dark +

**Comment by EliazTray** [comment]
thank you 👍

**Comment by newfoeother** [comment]
but i set "force" or "force-aligned"  is ok . when i set "force-expand-multiline", the code was broken, and i can't use js-beautify
