### ISSUE TITLE
format bugs: not supporting stylus in <style>

### ISSUE THREAD

**Issue by beeplin** [octref/vetur#78]
![image](https://cloud.githubusercontent.com/assets/13058150/23576632/a25d08c4-00e5-11e7-9ab4-b74c15393e9b.png)

stylus content without `{}`, `:` and `;` breaks into this after formatting:

![image](https://cloud.githubusercontent.com/assets/13058150/23576630/973f2c6a-00e5-11e7-9948-ccecf92b9fb1.png)

**Comment by octref** [comment]
Similar to #68. There is no formatter for stylus, jade or sass yet. I'll disable formatting for all these regions.

**Comment by beeplin** [comment]
Another thought: 

Anyway it's better to have a formatter than none. Now vetur just format stylus as if it is common css. If the stylus part has `{}`, `:` and `;` like css, it is formatted perfectly. It doesn't work only if we omit `{}`, `:` or `;`.

So how about this: Keep it what it behaves now, and in README just mention this trick:?

**Comment by beeplin** [comment]
coz in most cases we use stylus not because it can save some key presses for `{}` etc., but because we need to define and use stylus variables.

**Comment by octref** [comment]
I'll just disable it as most people don't write with {} and ; in stylus.

**Comment by octref** [comment]
Closing in favor of #82.
