### ISSUE TITLE
Highlights on Multiple Event Modifiers

### ISSUE THREAD

**Issue by crimx** [octref/vetur#79]
Highlights on multiple event modifiers seem buggy.

![_20170304204726](https://cloud.githubusercontent.com/assets/6882794/23578921/65829004-011c-11e7-830b-488c00b1946f.png)

**Comment by octref** [comment]
I'm marking the whole `@click.capture.stop` as http attributes and they will have the same syntax highlighting. (Previously `.` and `:` and `@` aren't colored).

![image](https://cloud.githubusercontent.com/assets/4033249/26747881/e0cd858e-47c6-11e7-9d9b-12250b2f1ac6.png)

This is in line with Vue's website's syntax highlight:

![image](https://cloud.githubusercontent.com/assets/4033249/26747877/d4463540-47c6-11e7-887f-a0328e679deb.png)
