### ISSUE TITLE
I want to support typescript

### ISSUE THREAD

**Issue by yeluoqiuzhi** [octref/vetur#8]
I want to support typescript

**Comment by octref** [comment]
This supports TS's syntax highlighting. You should subscribe to this issue: https://github.com/vuejs/vue/issues/478

I won't be looking into other features for supporting TS until there is one official integration between TS+Vue.

**Comment by Hanruis** [comment]
actually, you can separate js, html. css file  by  use src in vue file .
- so you can use scoped css easily
- you can use ts in vue single file & get the benifit of ts (like type check, intellisense)
