### ISSUE TITLE
Auto-completion of HTML tags with tab doesn't work

### ISSUE THREAD

**Issue by LanFeusT23** [octref/vetur#80]
Typing "div.route" for example or any kind of HTML followed by pressing TAB does not auto-complete to: <div class='route'></div>

This works fine in any html file, but not inside any .vue file. 

I've uninstalled and reinstalled both vetur and VS Code, but this no longer works.

**Comment by LanFeusT23** [comment]
It seems like my settings.json did not have:

```
"emmet.syntaxProfiles": {
        "vue-html": "html"
    }
```

Once added, it works fine. Although my work computer does not require that setting and it works fine as well as friend of mine, not sure why.

**Comment by octref** [comment]
Glad you resolved it by yourself.
Maybe you have an older version of vetur, or another vue extension on your work computer.

**Comment by LanFeusT23** [comment]
Could be, I'll be sure to check Monday! Great extension thanks! 👍
