### ISSUE TITLE
in@0.5.0, every time format will add a new line!

### ISSUE THREAD

**Issue by johnny19941216** [octref/vetur#84]
like this:
format before:
![image](https://cloud.githubusercontent.com/assets/15609400/23601992/392a8d36-0289-11e7-998a-0af0a48deb1d.png)
format after:
![image](https://cloud.githubusercontent.com/assets/15609400/23602006/4e557a68-0289-11e7-9276-bdf94dfe0fbc.png)
but format again:
![image](https://cloud.githubusercontent.com/assets/15609400/23602036/60b6b6d6-0289-11e7-8982-431e374138f1.png)
again and again and again:
![image](https://cloud.githubusercontent.com/assets/15609400/23602055/7aa3ef1e-0289-11e7-8579-15577fa0d2e7.png)

**Comment by octref** [comment]
The formatter is a bit broken now, see #82. I'll disable it completely in 0.5.1 and reenable once #82 is done.
