### ISSUE TITLE
Discrepency between Github README and VScode Readme

### ISSUE THREAD

**Issue by termleech** [octref/vetur#85]
In the README on GitHub it says for < 1.10 to change the file associated for .vue.  But in the README inside VSCode it says to make that change regardless of version.  Which is correct?

**Comment by octref** [comment]
Only set that for `< 1.10`. Interesting...Somehow vsce publish is not publishing my README. I'll look into this.

**Comment by termleech** [comment]
Awesome thank you. Keep up the amazing work.
