### ISSUE TITLE
Cannot format *.vue files

### ISSUE THREAD

**Issue by jiangshangzheng** [octref/vetur#86]

**Comment by likeswinds** [comment]
Cannot format

**Comment by ram-you** [comment]
@jiangshangzheng @likeswinds 

> Formatters are temporarily disabled until this feature is addressed.

See the issue https://github.com/octref/vetur/issues/82

**Comment by octref** [comment]
https://github.com/octref/vetur/issues/82#issuecomment-284454045

> Formatters are temporarily disabled until this feature is addressed.
