### ISSUE TITLE
wrongly display gitlens in <style>

### ISSUE THREAD

**Issue by beeplin** [octref/vetur#87]
When working together with [gitlens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) , .vue files <style> part has extra gitlens displays:

![image](https://cloud.githubusercontent.com/assets/13058150/23818266/a48679a6-0634-11e7-8a54-1df31d78b573.png)

I guess this is not a bug from gitlens, since if using other vue support plugins such as`vue` or `vue-component` there is no this issue. Simply renaming .vue file to .html file doesn't show the extra gitlens either. This happens only with vetur.

**Comment by octref** [comment]
Can you also open an issue at gitlens side? I don't quite know why it's happening, and I don't use gitlens.

**Comment by beeplin** [comment]
Here is the feedback from the author of gitlens:

@beeplin this is by design -- GitLens uses the symbol information provided by vscode to add its CodeLens (and extensions can extend/provide this symbol information). So the Vue extension must be providing a symbol for those classes.

You can control the behavior of the CodeLens via a few GitLens configuration settings (you can find the documentation for each setting here: https://github.com/eamodio/vscode-gitlens#extension-settings):
```
gitlens.codeLens.location
gitlens.codeLens.locationCustomSymbols
gitlens.codeLens.languageLocations
```
If you have any of the above set, please let me know how you have them configured.

Also if you upgrade to v2.12.1, you can also set `"gitlens.advanced.codeLens.debug" = true` which will add debug information into the CodeLens themselves (symbol name, line range, etc). If you turn that on, and send a screenshot I can help you configure your settings appropriately.

**Comment by octref** [comment]
Let's keep this issue open on the GitLens side.
