### ISSUE TITLE
Cannot start debugger server

### ISSUE THREAD

**Issue by formulahendry** [octref/vetur#88]
First, thanks for your extension~

Problem 1: Not sure why this error happened
Problem 2: It will always create a debug.log in workspace root and it will make the source control dirty.

![image](https://cloud.githubusercontent.com/assets/1050213/23841060/789c6adc-07e5-11e7-98c5-e6d813bcffc0.png)

**Comment by octref** [comment]
Haven't seen this before. Are you running a linux box and have some sort of rule that limits use of port 6004?

**Comment by formulahendry** [comment]
I am using Windows 10. I have not set any rules on 6004.
![image](https://cloud.githubusercontent.com/assets/1050213/23841807/dac73084-07ea-11e7-8d44-171b97dbe49e.png)
I am ok for this kind of error since currently I have not used the debug feature. The pain point is that it will  automatically create a debug.log file. Not good experience for user.

**Comment by octref** [comment]
This extension doesn't provide any debug feature -- how are you using the debug feature then?

**Comment by formulahendry** [comment]
I just see 'Cannot start debugger server' the error message and it let me think it has a debug feature in Language Server. Anyway, I just want the basic IntelliSense and highlight feature.  And this bug really trouble me and I need to add debug,log into gitignore.
I think the debug.log file would better not be created automatically or provide an config for user. Generally, the Output Channel in enough.

**Comment by octref** [comment]
That is unintended. I'll try to fix that.

Maybe it's because VSCode's html LS is conflicting with vetur on port 6004. Would you mind trying this?

- Go to `%USERPROFILE%\.vscode\extensions\octref.vetur-0.5.1`
- Find `client/out/htmlMain.js`
- Replace `--debug=6004` with `--debug=6005`
- Restart VSCode on your project to see if it happens again

**Comment by formulahendry** [comment]
No error now. Thanks!

**Comment by octref** [comment]
I'll include the fix in the next version.
