### ISSUE TITLE
Integration with eslint

### ISSUE THREAD

**Issue by ugros** [octref/vetur#89]
My (maybe impossible or pretty hard to implement) requests are:

1. integration with Eslint (error checks, possible eslint-autofix support)
2. make default exported class "this" context integrated in template (for example properties not-defined in either data/computed/methods would throw "eslint not defined variable" error.

Anyway, thanks for the great work on this extension so far!

**Comment by octref** [comment]
1. You can already use ESLint, see https://github.com/octref/vetur#setup
Autofix seems to be supported by the ESLint plugin: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

2. It's possible to do that after #75.

**Comment by octref** [comment]
Thanks for your suggestion and encouraging words.
Will consider again after #75.

**Comment by ugros** [comment]
Thanks for the answer.

I am using Eslint extension already, and it work's great for javascript code inside <script> tag.

But what I originaly meant is eslint for javascript code inside <template> tag, i.e. v-if="condition == variable" should throw eslint "eqeqeq" warning (comparing values with == instead of ===)

**Comment by octref** [comment]
Tracking that with #96.
