### ISSUE TITLE
The Vetur plugin result in the emmet of VS Code invalidate.

### ISSUE THREAD

**Issue by usercao** [octref/vetur#90]
![code img](http://p1.bpimg.com/580149/e00b7381d475b54b.png)
After setup the Vetur  plugin, the emmet  auto-complete function of  VS Code will invalidate.

**Comment by octref** [comment]
It's the first thing in readme.

![image](https://cloud.githubusercontent.com/assets/4033249/23980405/bc8837d4-09d5-11e7-99fa-c9a476c6083a.png)
