### ISSUE TITLE
CSS error checking inactive

### ISSUE THREAD

**Issue by ronjouch** [octref/vetur#91]
The doc says vetur provides "Error checking for css/scss/less", but it doesn't seem active in the `<style>` section of .vue files. See screenshot below:

* Left: the vscode `[css]` checker reports errors in a `.css` file
* Right: no error reported for CSS in the `<style>` section of a `.vue` file

![vetur-css-linting-broken-vue-files](https://cloud.githubusercontent.com/assets/522085/24002147/5eaa1248-0a36-11e7-916e-1e4b2b4b6285.png)

Am I missing something? Is there undocumented configuration required to activate CSS linting / error checking in the `<style>` section of `.vue` files?

*EDIT: by the way, the doc mentions both CSS "error checking" and "linting". Does vetur support the two of them? If linting, which linter and is there required installation/configuration?*

* vetur 0.5.3 under code 1.10.2
* No specific settings except adding `, "vue"` to `"eslint.validate"` for in-`<script>` eslinting (which works fine, as you can see in the screenshot)
* No other Vue extension installed

**Comment by octref** [comment]
Short answer is css embedded in vue is using a reduced version of VSCode's css language service, which itself only has limited support for error checking & linting.

Long answer is following recent changes in formatter(#82), I think it's better to move off the error checking and linting part from VSCode's hand-written css language service to more robust solutions actively maintained by communities like:

- https://github.com/stylelint/stylelint
- https://github.com/brigade/scss-lint

**Comment by ronjouch** [comment]
Problem fixed with 0.5.4, thanks 👍

Great if stylelint/scss-lint integration arrives someday, for now I'm happy with vscode's basic checking.

**Comment by octref** [comment]
Just meant to mention 0.5.4 would re-enable css/scss/less error checking.
This was lost while porting new changes from VSCode's html extension.
