### ISSUE TITLE
scss/less error checking

### ISSUE THREAD

**Issue by tangdw** [octref/vetur#95]
script 里的 js 代码报 [less] 错误

**Comment by Li-Alex** [comment]
Is it the same problem ?
![image](https://cloud.githubusercontent.com/assets/16162468/24026413/e9d80558-0afb-11e7-8821-05747c43686b.png)

**Comment by octref** [comment]
Can you provide a reproducible case?

**Comment by Li-Alex** [comment]
try to write the script tag after style tag
![image](https://cloud.githubusercontent.com/assets/16162468/24027032/bb465470-0aff-11e7-97c1-0883dac582f9.png)

**Comment by octref** [comment]
@Li-Alex Thanks. I'll fix it for next version.

**Comment by octref** [comment]
Fixed in 0.5.5.
